// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;

import 'dart:typed_data' as i2;

import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    localMeta,
    syncState,
    installedPublication,
    publicationFile,
    fileBlob,
    siteData,
    siteSearch,
  ];
  late final Shape0 localMeta = Shape0(
    source: i0.VersionedTable(
      entityName: 'local_meta',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 syncState = Shape1(
    source: i0.VersionedTable(
      entityName: 'sync_state',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'CHECK(id = 1)'],
      columns: [
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 installedPublication = Shape2(
    source: i0.VersionedTable(
      entityName: 'installed_publication',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(site_id)'],
      columns: [
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 publicationFile = Shape3(
    source: i0.VersionedTable(
      entityName: 'publication_file',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(publication_id, path)'],
      columns: [
        _column_14,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 fileBlob = Shape4(
    source: i0.VersionedTable(
      entityName: 'file_blob',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(sha256)'],
      columns: [_column_25, _column_26, _column_29, _column_30],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 siteData = Shape5(
    source: i0.VersionedTable(
      entityName: 'site_data',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(site_id)'],
      columns: [_column_13, _column_14, _column_31],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 siteSearch = Shape6(
    source: i0.VersionedTable(
      entityName: 'site_search',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(site_id)'],
      columns: [
        _column_13,
        _column_32,
        _column_20,
        _column_33,
        _column_34,
        _column_35,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get value =>
      columnsByName['value']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'value',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get activeGeneration =>
      columnsByName['active_generation']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get lastSyncAt =>
      columnsByName['last_sync_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get catalogGeneration =>
      columnsByName['catalog_generation']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get lastAttemptAt =>
      columnsByName['last_attempt_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastError =>
      columnsByName['last_error']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get serverTime =>
      columnsByName['server_time']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get authorizedUserId =>
      columnsByName['authorized_user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get authorizationExpiresAt =>
      columnsByName['authorization_expires_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get receiptPending =>
      columnsByName['receipt_pending']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_2(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_3(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'active_generation',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_sync_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'never\'',
      defaultValue: const i1.CustomExpression('\'never\''),
    );
i1.GeneratedColumn<int> _column_6(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'catalog_generation',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_attempt_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_error',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'server_time',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'authorized_user_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'authorization_expires_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_12(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'receipt_pending',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 0 CHECK (receipt_pending IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get siteId =>
      columnsByName['site_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get publicationId =>
      columnsByName['publication_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get publicationNumber =>
      columnsByName['publication_number']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get manifestHash =>
      columnsByName['manifest_hash']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get manifestText =>
      columnsByName['manifest_text']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get signatureKeyId =>
      columnsByName['signature_key_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get signature =>
      columnsByName['signature']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get etareNumber =>
      columnsByName['etare_number']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get siteName =>
      columnsByName['site_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get publishedAt =>
      columnsByName['published_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get installedAt =>
      columnsByName['installed_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'site_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'publication_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'publication_number',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'manifest_hash',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'manifest_text',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'signature_key_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'signature',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'etare_number',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_21(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'site_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'published_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'installed_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get publicationId =>
      columnsByName['publication_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get path =>
      columnsByName['path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sha256 =>
      columnsByName['sha256']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sizeBytes =>
      columnsByName['size_bytes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get mediaType =>
      columnsByName['media_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get required =>
      columnsByName['required']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'path',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sha256',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_26(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'size_bytes',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'media_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_28(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'required',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (required IN (0, 1))',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get sha256 =>
      columnsByName['sha256']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sizeBytes =>
      columnsByName['size_bytes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<i2.Uint8List> get content =>
      columnsByName['content']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<String> get storedAt =>
      columnsByName['stored_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<i2.Uint8List> _column_29(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'content',
      aliasedName,
      false,
      type: i1.DriftSqlType.blob,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'stored_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get siteId =>
      columnsByName['site_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get publicationId =>
      columnsByName['publication_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get dataText =>
      columnsByName['data_text']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'data_text',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get siteId =>
      columnsByName['site_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get etareNumber =>
      columnsByName['etare_number']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get addressLabel =>
      columnsByName['address_label']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get city =>
      columnsByName['city']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get searchText =>
      columnsByName['search_text']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'address_label',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'city',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'search_text',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    localMeta,
    syncState,
    installedPublication,
    publicationFile,
    fileBlob,
    siteData,
    siteSearch,
    fieldReport,
    fieldReportPhoto,
  ];
  late final Shape0 localMeta = Shape0(
    source: i0.VersionedTable(
      entityName: 'local_meta',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 syncState = Shape1(
    source: i0.VersionedTable(
      entityName: 'sync_state',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'CHECK(id = 1)'],
      columns: [
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 installedPublication = Shape2(
    source: i0.VersionedTable(
      entityName: 'installed_publication',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(site_id)'],
      columns: [
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 publicationFile = Shape3(
    source: i0.VersionedTable(
      entityName: 'publication_file',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(publication_id, path)'],
      columns: [
        _column_14,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 fileBlob = Shape4(
    source: i0.VersionedTable(
      entityName: 'file_blob',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(sha256)'],
      columns: [_column_25, _column_26, _column_29, _column_30],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 siteData = Shape5(
    source: i0.VersionedTable(
      entityName: 'site_data',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(site_id)'],
      columns: [_column_13, _column_14, _column_31],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 siteSearch = Shape6(
    source: i0.VersionedTable(
      entityName: 'site_search',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(site_id)'],
      columns: [
        _column_13,
        _column_32,
        _column_20,
        _column_33,
        _column_34,
        _column_35,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 fieldReport = Shape7(
    source: i0.VersionedTable(
      entityName: 'field_report',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(client_report_id)'],
      columns: [
        _column_36,
        _column_37,
        _column_38,
        _column_13,
        _column_21,
        _column_14,
        _column_15,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_8,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
        _column_58,
        _column_59,
        _column_60,
        _column_61,
        _column_62,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 fieldReportPhoto = Shape8(
    source: i0.VersionedTable(
      entityName: 'field_report_photo',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(client_report_id, position)'],
      columns: [
        _column_63,
        _column_64,
        _column_25,
        _column_65,
        _column_66,
        _column_29,
        _column_67,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get clientReportId =>
      columnsByName['client_report_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get authorUserId =>
      columnsByName['author_user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get tenantId =>
      columnsByName['tenant_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get siteId =>
      columnsByName['site_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get siteName =>
      columnsByName['site_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get publicationId =>
      columnsByName['publication_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get publicationNumber =>
      columnsByName['publication_number']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get category =>
      columnsByName['category']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get severity =>
      columnsByName['severity']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get observedAt =>
      columnsByName['observed_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get itemType =>
      columnsByName['item_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get itemId =>
      columnsByName['item_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get itemLabel =>
      columnsByName['item_label']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get planRevisionId =>
      columnsByName['plan_revision_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get planTitle =>
      columnsByName['plan_title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get planX =>
      columnsByName['plan_x']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get planY =>
      columnsByName['plan_y']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get photoCount =>
      columnsByName['photo_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get localState =>
      columnsByName['local_state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastError =>
      columnsByName['last_error']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get attempts =>
      columnsByName['attempts']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get nextAttemptAt =>
      columnsByName['next_attempt_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get serverReportId =>
      columnsByName['server_report_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get contentHash =>
      columnsByName['content_hash']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get receivedAt =>
      columnsByName['received_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get serverStatus =>
      columnsByName['server_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get decisionComment =>
      columnsByName['decision_comment']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get decidedAt =>
      columnsByName['decided_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get resolutionRevisionNo =>
      columnsByName['resolution_revision_no']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get resolutionPublicationNumber =>
      columnsByName['resolution_publication_number']!
          as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'client_report_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'author_user_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_38(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tenant_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_39(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'category',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_40(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'severity',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'description',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'observed_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_43(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'item_type',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_44(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'item_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_45(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'item_label',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_46(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'plan_revision_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_47(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'plan_title',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_48(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'plan_x',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_49(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'plan_y',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_50(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'photo_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_51(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'local_state',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'pending\'',
      defaultValue: const i1.CustomExpression('\'pending\''),
    );
i1.GeneratedColumn<int> _column_52(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'attempts',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_53(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'next_attempt_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_54(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'server_report_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_55(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'content_hash',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_56(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'received_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_57(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'server_status',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_58(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'decision_comment',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_59(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'decided_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_60(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'resolution_revision_no',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_61(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'resolution_publication_number',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_62(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get clientReportId =>
      columnsByName['client_report_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get position =>
      columnsByName['position']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get sha256 =>
      columnsByName['sha256']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mimeType =>
      columnsByName['mime_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get filename =>
      columnsByName['filename']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<i2.Uint8List> get content =>
      columnsByName['content']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<int> get uploaded =>
      columnsByName['uploaded']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_63(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'client_report_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL REFERENCES field_report(client_report_id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<int> _column_64(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'position',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_65(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'mime_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_66(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'filename',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_67(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'uploaded',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (uploaded IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    localMeta,
    syncState,
    installedPublication,
    publicationFile,
    fileBlob,
    siteData,
    siteSearch,
    fieldReport,
    fieldReportPhoto,
  ];
  late final Shape0 localMeta = Shape0(
    source: i0.VersionedTable(
      entityName: 'local_meta',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 syncState = Shape9(
    source: i0.VersionedTable(
      entityName: 'sync_state',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'CHECK(id = 1)'],
      columns: [
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_68,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 installedPublication = Shape2(
    source: i0.VersionedTable(
      entityName: 'installed_publication',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(site_id)'],
      columns: [
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 publicationFile = Shape3(
    source: i0.VersionedTable(
      entityName: 'publication_file',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(publication_id, path)'],
      columns: [
        _column_14,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 fileBlob = Shape4(
    source: i0.VersionedTable(
      entityName: 'file_blob',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(sha256)'],
      columns: [_column_25, _column_26, _column_29, _column_30],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 siteData = Shape5(
    source: i0.VersionedTable(
      entityName: 'site_data',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(site_id)'],
      columns: [_column_13, _column_14, _column_31],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 siteSearch = Shape6(
    source: i0.VersionedTable(
      entityName: 'site_search',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(site_id)'],
      columns: [
        _column_13,
        _column_32,
        _column_20,
        _column_33,
        _column_34,
        _column_35,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 fieldReport = Shape7(
    source: i0.VersionedTable(
      entityName: 'field_report',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(client_report_id)'],
      columns: [
        _column_36,
        _column_37,
        _column_38,
        _column_13,
        _column_21,
        _column_14,
        _column_15,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_8,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
        _column_58,
        _column_59,
        _column_60,
        _column_61,
        _column_62,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 fieldReportPhoto = Shape8(
    source: i0.VersionedTable(
      entityName: 'field_report_photo',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(client_report_id, position)'],
      columns: [
        _column_63,
        _column_64,
        _column_25,
        _column_65,
        _column_66,
        _column_29,
        _column_67,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get activeGeneration =>
      columnsByName['active_generation']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get lastSyncAt =>
      columnsByName['last_sync_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get catalogGeneration =>
      columnsByName['catalog_generation']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get lastAttemptAt =>
      columnsByName['last_attempt_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastError =>
      columnsByName['last_error']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get serverTime =>
      columnsByName['server_time']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get authorizedUserId =>
      columnsByName['authorized_user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get authorizationExpiresAt =>
      columnsByName['authorization_expires_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get receiptPending =>
      columnsByName['receipt_pending']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get requiredAppVersion =>
      columnsByName['required_app_version']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_68(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'required_app_version',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

final class Schema5 extends i0.VersionedSchema {
  Schema5({required super.database}) : super(version: 5);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    localMeta,
    syncState,
    installedPublication,
    publicationFile,
    fileBlob,
    siteData,
    siteSearch,
    fieldReport,
    fieldReportPhoto,
  ];
  late final Shape0 localMeta = Shape0(
    source: i0.VersionedTable(
      entityName: 'local_meta',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 syncState = Shape10(
    source: i0.VersionedTable(
      entityName: 'sync_state',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'CHECK(id = 1)'],
      columns: [
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_68,
        _column_69,
        _column_70,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 installedPublication = Shape2(
    source: i0.VersionedTable(
      entityName: 'installed_publication',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(site_id)'],
      columns: [
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 publicationFile = Shape3(
    source: i0.VersionedTable(
      entityName: 'publication_file',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(publication_id, path)'],
      columns: [
        _column_14,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 fileBlob = Shape4(
    source: i0.VersionedTable(
      entityName: 'file_blob',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(sha256)'],
      columns: [_column_25, _column_26, _column_29, _column_30],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 siteData = Shape5(
    source: i0.VersionedTable(
      entityName: 'site_data',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(site_id)'],
      columns: [_column_13, _column_14, _column_31],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 siteSearch = Shape6(
    source: i0.VersionedTable(
      entityName: 'site_search',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(site_id)'],
      columns: [
        _column_13,
        _column_32,
        _column_20,
        _column_33,
        _column_34,
        _column_35,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 fieldReport = Shape7(
    source: i0.VersionedTable(
      entityName: 'field_report',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(client_report_id)'],
      columns: [
        _column_36,
        _column_37,
        _column_38,
        _column_13,
        _column_21,
        _column_14,
        _column_15,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_8,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
        _column_58,
        _column_59,
        _column_60,
        _column_61,
        _column_62,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 fieldReportPhoto = Shape8(
    source: i0.VersionedTable(
      entityName: 'field_report_photo',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(client_report_id, position)'],
      columns: [
        _column_63,
        _column_64,
        _column_25,
        _column_65,
        _column_66,
        _column_29,
        _column_67,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get activeGeneration =>
      columnsByName['active_generation']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get lastSyncAt =>
      columnsByName['last_sync_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get catalogGeneration =>
      columnsByName['catalog_generation']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get lastAttemptAt =>
      columnsByName['last_attempt_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastError =>
      columnsByName['last_error']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get serverTime =>
      columnsByName['server_time']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get authorizedUserId =>
      columnsByName['authorized_user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get authorizationExpiresAt =>
      columnsByName['authorization_expires_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get receiptPending =>
      columnsByName['receipt_pending']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get requiredAppVersion =>
      columnsByName['required_app_version']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get syncLeaseOwner =>
      columnsByName['sync_lease_owner']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get syncLeaseExpiresAt =>
      columnsByName['sync_lease_expires_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_69(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sync_lease_owner',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_70(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sync_lease_expires_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

final class Schema6 extends i0.VersionedSchema {
  Schema6({required super.database}) : super(version: 6);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    localMeta,
    syncState,
    installedPublication,
    publicationFile,
    fileBlob,
    siteData,
    siteSearch,
    fieldReport,
    fieldReportPhoto,
    onDemandSites,
    sensitiveSites,
    sensitiveFiles,
    accessEventOutbox,
  ];
  late final Shape0 localMeta = Shape0(
    source: i0.VersionedTable(
      entityName: 'local_meta',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 syncState = Shape10(
    source: i0.VersionedTable(
      entityName: 'sync_state',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'CHECK(id = 1)'],
      columns: [
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_68,
        _column_69,
        _column_70,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 installedPublication = Shape2(
    source: i0.VersionedTable(
      entityName: 'installed_publication',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(site_id)'],
      columns: [
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 publicationFile = Shape3(
    source: i0.VersionedTable(
      entityName: 'publication_file',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(publication_id, path)'],
      columns: [
        _column_14,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 fileBlob = Shape4(
    source: i0.VersionedTable(
      entityName: 'file_blob',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(sha256)'],
      columns: [_column_25, _column_26, _column_29, _column_30],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 siteData = Shape5(
    source: i0.VersionedTable(
      entityName: 'site_data',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(site_id)'],
      columns: [_column_13, _column_14, _column_31],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 siteSearch = Shape6(
    source: i0.VersionedTable(
      entityName: 'site_search',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(site_id)'],
      columns: [
        _column_13,
        _column_32,
        _column_20,
        _column_33,
        _column_34,
        _column_35,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 fieldReport = Shape7(
    source: i0.VersionedTable(
      entityName: 'field_report',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(client_report_id)'],
      columns: [
        _column_36,
        _column_37,
        _column_38,
        _column_13,
        _column_21,
        _column_14,
        _column_15,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_8,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
        _column_58,
        _column_59,
        _column_60,
        _column_61,
        _column_62,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 fieldReportPhoto = Shape8(
    source: i0.VersionedTable(
      entityName: 'field_report_photo',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(client_report_id, position)'],
      columns: [
        _column_63,
        _column_64,
        _column_25,
        _column_65,
        _column_66,
        _column_29,
        _column_67,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 onDemandSites = Shape11(
    source: i0.VersionedTable(
      entityName: 'on_demand_sites',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(site_id)'],
      columns: [
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_21,
        _column_20,
        _column_26,
        _column_22,
        _column_35,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 sensitiveSites = Shape12(
    source: i0.VersionedTable(
      entityName: 'sensitive_sites',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(site_id)'],
      columns: [
        _column_13,
        _column_14,
        _column_15,
        _column_71,
        _column_21,
        _column_72,
        _column_73,
        _column_74,
        _column_75,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 sensitiveFiles = Shape13(
    source: i0.VersionedTable(
      entityName: 'sensitive_files',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(site_id, sha256)'],
      columns: [_column_13, _column_25, _column_24, _column_27, _column_76],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 accessEventOutbox = Shape14(
    source: i0.VersionedTable(
      entityName: 'access_event_outbox',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(client_event_id)'],
      columns: [_column_77, _column_71, _column_13, _column_14, _column_78],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get siteId =>
      columnsByName['site_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get publicationId =>
      columnsByName['publication_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get publicationNumber =>
      columnsByName['publication_number']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get manifestHash =>
      columnsByName['manifest_hash']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get siteName =>
      columnsByName['site_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get etareNumber =>
      columnsByName['etare_number']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sizeBytes =>
      columnsByName['size_bytes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get publishedAt =>
      columnsByName['published_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get searchText =>
      columnsByName['search_text']! as i1.GeneratedColumn<String>;
}

class Shape12 extends i0.VersionedTable {
  Shape12({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get siteId =>
      columnsByName['site_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get publicationId =>
      columnsByName['publication_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get publicationNumber =>
      columnsByName['publication_number']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get siteName =>
      columnsByName['site_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get openedAt =>
      columnsByName['opened_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get expiresAt =>
      columnsByName['expires_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<i2.Uint8List> get wrappedKey =>
      columnsByName['wrapped_key']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<i2.Uint8List> get dataCipher =>
      columnsByName['data_cipher']! as i1.GeneratedColumn<i2.Uint8List>;
}

i1.GeneratedColumn<String> _column_71(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'user_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_72(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'opened_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_73(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'expires_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<i2.Uint8List> _column_74(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'wrapped_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.blob,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<i2.Uint8List> _column_75(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'data_cipher',
      aliasedName,
      false,
      type: i1.DriftSqlType.blob,
      $customConstraints: 'NOT NULL',
    );

class Shape13 extends i0.VersionedTable {
  Shape13({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get siteId =>
      columnsByName['site_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sha256 =>
      columnsByName['sha256']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get path =>
      columnsByName['path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mediaType =>
      columnsByName['media_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<i2.Uint8List> get cipher =>
      columnsByName['cipher']! as i1.GeneratedColumn<i2.Uint8List>;
}

i1.GeneratedColumn<i2.Uint8List> _column_76(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'cipher',
      aliasedName,
      false,
      type: i1.DriftSqlType.blob,
      $customConstraints: 'NOT NULL',
    );

class Shape14 extends i0.VersionedTable {
  Shape14({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get clientEventId =>
      columnsByName['client_event_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get siteId =>
      columnsByName['site_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get publicationId =>
      columnsByName['publication_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get occurredAt =>
      columnsByName['occurred_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_77(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'client_event_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_78(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'occurred_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

final class Schema7 extends i0.VersionedSchema {
  Schema7({required super.database}) : super(version: 7);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    localMeta,
    syncState,
    installedPublication,
    publicationFile,
    fileBlob,
    siteData,
    siteSearch,
    fieldReport,
    fieldReportPhoto,
    onDemandSites,
    sensitiveSites,
    sensitiveFiles,
    accessEventOutbox,
    installedBasemaps,
  ];
  late final Shape0 localMeta = Shape0(
    source: i0.VersionedTable(
      entityName: 'local_meta',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 syncState = Shape10(
    source: i0.VersionedTable(
      entityName: 'sync_state',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'CHECK(id = 1)'],
      columns: [
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_68,
        _column_69,
        _column_70,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 installedPublication = Shape2(
    source: i0.VersionedTable(
      entityName: 'installed_publication',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(site_id)'],
      columns: [
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 publicationFile = Shape3(
    source: i0.VersionedTable(
      entityName: 'publication_file',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(publication_id, path)'],
      columns: [
        _column_14,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 fileBlob = Shape4(
    source: i0.VersionedTable(
      entityName: 'file_blob',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(sha256)'],
      columns: [_column_25, _column_26, _column_29, _column_30],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 siteData = Shape5(
    source: i0.VersionedTable(
      entityName: 'site_data',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(site_id)'],
      columns: [_column_13, _column_14, _column_31],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 siteSearch = Shape6(
    source: i0.VersionedTable(
      entityName: 'site_search',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(site_id)'],
      columns: [
        _column_13,
        _column_32,
        _column_20,
        _column_33,
        _column_34,
        _column_35,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 fieldReport = Shape7(
    source: i0.VersionedTable(
      entityName: 'field_report',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(client_report_id)'],
      columns: [
        _column_36,
        _column_37,
        _column_38,
        _column_13,
        _column_21,
        _column_14,
        _column_15,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_8,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
        _column_58,
        _column_59,
        _column_60,
        _column_61,
        _column_62,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 fieldReportPhoto = Shape8(
    source: i0.VersionedTable(
      entityName: 'field_report_photo',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(client_report_id, position)'],
      columns: [
        _column_63,
        _column_64,
        _column_25,
        _column_65,
        _column_66,
        _column_29,
        _column_67,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 onDemandSites = Shape11(
    source: i0.VersionedTable(
      entityName: 'on_demand_sites',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(site_id)'],
      columns: [
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_21,
        _column_20,
        _column_26,
        _column_22,
        _column_35,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 sensitiveSites = Shape12(
    source: i0.VersionedTable(
      entityName: 'sensitive_sites',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(site_id)'],
      columns: [
        _column_13,
        _column_14,
        _column_15,
        _column_71,
        _column_21,
        _column_72,
        _column_73,
        _column_74,
        _column_75,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 sensitiveFiles = Shape13(
    source: i0.VersionedTable(
      entityName: 'sensitive_files',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(site_id, sha256)'],
      columns: [_column_13, _column_25, _column_24, _column_27, _column_76],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 accessEventOutbox = Shape14(
    source: i0.VersionedTable(
      entityName: 'access_event_outbox',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(client_event_id)'],
      columns: [_column_77, _column_71, _column_13, _column_14, _column_78],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape15 installedBasemaps = Shape15(
    source: i0.VersionedTable(
      entityName: 'installed_basemaps',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(pack_id)'],
      columns: [
        _column_79,
        _column_80,
        _column_81,
        _column_82,
        _column_16,
        _column_17,
        _column_83,
        _column_84,
        _column_85,
        _column_23,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape15 extends i0.VersionedTable {
  Shape15({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get packId =>
      columnsByName['pack_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sectorId =>
      columnsByName['sector_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sectorName =>
      columnsByName['sector_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get version =>
      columnsByName['version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get manifestHash =>
      columnsByName['manifest_hash']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get manifestText =>
      columnsByName['manifest_text']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get totalBytes =>
      columnsByName['total_bytes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get builtAt =>
      columnsByName['built_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get renewAfter =>
      columnsByName['renew_after']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get installedAt =>
      columnsByName['installed_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_79(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'pack_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_80(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sector_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_81(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sector_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_82(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'version',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_83(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'total_bytes',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_84(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'built_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_85(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'renew_after',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

final class Schema8 extends i0.VersionedSchema {
  Schema8({required super.database}) : super(version: 8);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    localMeta,
    syncState,
    installedPublication,
    publicationFile,
    fileBlob,
    siteData,
    siteSearch,
    fieldReport,
    fieldReportPhoto,
    onDemandSites,
    sensitiveSites,
    sensitiveFiles,
    accessEventOutbox,
    installedBasemaps,
    trustedKeyset,
  ];
  late final Shape0 localMeta = Shape0(
    source: i0.VersionedTable(
      entityName: 'local_meta',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 syncState = Shape10(
    source: i0.VersionedTable(
      entityName: 'sync_state',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'CHECK(id = 1)'],
      columns: [
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_68,
        _column_69,
        _column_70,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 installedPublication = Shape2(
    source: i0.VersionedTable(
      entityName: 'installed_publication',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(site_id)'],
      columns: [
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 publicationFile = Shape3(
    source: i0.VersionedTable(
      entityName: 'publication_file',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(publication_id, path)'],
      columns: [
        _column_14,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 fileBlob = Shape4(
    source: i0.VersionedTable(
      entityName: 'file_blob',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(sha256)'],
      columns: [_column_25, _column_26, _column_29, _column_30],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 siteData = Shape5(
    source: i0.VersionedTable(
      entityName: 'site_data',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(site_id)'],
      columns: [_column_13, _column_14, _column_31],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 siteSearch = Shape6(
    source: i0.VersionedTable(
      entityName: 'site_search',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(site_id)'],
      columns: [
        _column_13,
        _column_32,
        _column_20,
        _column_33,
        _column_34,
        _column_35,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 fieldReport = Shape7(
    source: i0.VersionedTable(
      entityName: 'field_report',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(client_report_id)'],
      columns: [
        _column_36,
        _column_37,
        _column_38,
        _column_13,
        _column_21,
        _column_14,
        _column_15,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_8,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
        _column_58,
        _column_59,
        _column_60,
        _column_61,
        _column_62,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 fieldReportPhoto = Shape8(
    source: i0.VersionedTable(
      entityName: 'field_report_photo',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(client_report_id, position)'],
      columns: [
        _column_63,
        _column_64,
        _column_25,
        _column_65,
        _column_66,
        _column_29,
        _column_67,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 onDemandSites = Shape11(
    source: i0.VersionedTable(
      entityName: 'on_demand_sites',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(site_id)'],
      columns: [
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_21,
        _column_20,
        _column_26,
        _column_22,
        _column_35,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 sensitiveSites = Shape12(
    source: i0.VersionedTable(
      entityName: 'sensitive_sites',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(site_id)'],
      columns: [
        _column_13,
        _column_14,
        _column_15,
        _column_71,
        _column_21,
        _column_72,
        _column_73,
        _column_74,
        _column_75,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 sensitiveFiles = Shape13(
    source: i0.VersionedTable(
      entityName: 'sensitive_files',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(site_id, sha256)'],
      columns: [_column_13, _column_25, _column_24, _column_27, _column_76],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 accessEventOutbox = Shape14(
    source: i0.VersionedTable(
      entityName: 'access_event_outbox',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(client_event_id)'],
      columns: [_column_77, _column_71, _column_13, _column_14, _column_78],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape16 installedBasemaps = Shape16(
    source: i0.VersionedTable(
      entityName: 'installed_basemaps',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(pack_id)'],
      columns: [
        _column_79,
        _column_80,
        _column_81,
        _column_82,
        _column_16,
        _column_17,
        _column_83,
        _column_84,
        _column_85,
        _column_23,
        _column_86,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape17 trustedKeyset = Shape17(
    source: i0.VersionedTable(
      entityName: 'trusted_keyset',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'CHECK(id = 1)'],
      columns: [
        _column_2,
        _column_87,
        _column_88,
        _column_89,
        _column_19,
        _column_90,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape16 extends i0.VersionedTable {
  Shape16({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get packId =>
      columnsByName['pack_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sectorId =>
      columnsByName['sector_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sectorName =>
      columnsByName['sector_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get version =>
      columnsByName['version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get manifestHash =>
      columnsByName['manifest_hash']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get manifestText =>
      columnsByName['manifest_text']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get totalBytes =>
      columnsByName['total_bytes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get builtAt =>
      columnsByName['built_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get renewAfter =>
      columnsByName['renew_after']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get installedAt =>
      columnsByName['installed_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get signatureKeyId =>
      columnsByName['signature_key_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_86(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'signature_key_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape17 extends i0.VersionedTable {
  Shape17({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get sequence =>
      columnsByName['sequence']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get keysetText =>
      columnsByName['keyset_text']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get rootKeyId =>
      columnsByName['root_key_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get signature =>
      columnsByName['signature']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get receivedAt =>
      columnsByName['received_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_87(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'sequence',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_88(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'keyset_text',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_89(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'root_key_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_90(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'received_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
  required Future<void> Function(i1.Migrator m, Schema7 schema) from6To7,
  required Future<void> Function(i1.Migrator m, Schema8 schema) from7To8,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      case 4:
        final schema = Schema5(database: database);
        final migrator = i1.Migrator(database, schema);
        await from4To5(migrator, schema);
        return 5;
      case 5:
        final schema = Schema6(database: database);
        final migrator = i1.Migrator(database, schema);
        await from5To6(migrator, schema);
        return 6;
      case 6:
        final schema = Schema7(database: database);
        final migrator = i1.Migrator(database, schema);
        await from6To7(migrator, schema);
        return 7;
      case 7:
        final schema = Schema8(database: database);
        final migrator = i1.Migrator(database, schema);
        await from7To8(migrator, schema);
        return 8;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
  required Future<void> Function(i1.Migrator m, Schema7 schema) from6To7,
  required Future<void> Function(i1.Migrator m, Schema8 schema) from7To8,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(
    from1To2: from1To2,
    from2To3: from2To3,
    from3To4: from3To4,
    from4To5: from4To5,
    from5To6: from5To6,
    from6To7: from6To7,
    from7To8: from7To8,
  ),
);
