'use client';

import { totpCodeSchema } from '@etare/schemas';
import { Alert, Badge, Button, Field, Input, Skeleton } from '@etare/ui';
import { zodResolver } from '@hookform/resolvers/zod';
import { useQuery } from '@tanstack/react-query';
import { ShieldCheck } from 'lucide-react';
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import {
  MfaError,
  listTotpFactors,
  removeTotpFactor,
  startTotpEnrollment,
  verifyTotp,
  type TotpEnrollment,
} from '@/lib/mfa';

const dateFormat = new Intl.DateTimeFormat('fr-FR', { dateStyle: 'long', timeZone: 'Europe/Paris' });
const codeForm = z.object({ code: totpCodeSchema });
type CodeValues = z.infer<typeof codeForm>;

const messageOf = (error: unknown) =>
  error instanceof MfaError ? error.message : 'Le service d’authentification est injoignable. Réessayez.';

/** Readable groups of 4 characters for manual entry of the secret. */
const groups = (secret: string) => secret.replace(/(.{4})/g, '$1 ').trim();

function EnrollmentForm({ enrollment, onDone }: { enrollment: TotpEnrollment; onDone: () => void }) {
  const [failure, setFailure] = useState<string | null>(null);
  const {
    register,
    handleSubmit,
    formState: { errors, isSubmitting },
  } = useForm<CodeValues>({ resolver: zodResolver(codeForm), defaultValues: { code: '' } });

  return (
    <form
      noValidate
      className="space-y-4"
      onSubmit={handleSubmit(async ({ code }) => {
        setFailure(null);
        try {
          await verifyTotp(enrollment.factorId, code);
          onDone();
        } catch (error) {
          setFailure(messageOf(error));
        }
      })}
    >
      <ol className="list-decimal space-y-3 pl-5 text-sm">
        <li>
          Scannez ce code avec votre application d’authentification (FreeOTP, Microsoft Authenticator, Google
          Authenticator…).
          {/* eslint-disable-next-line @next/next/no-img-element -- data URI generated by the identity provider */}
          <img
            src={enrollment.qrCode}
            alt="QR code d’activation"
            className="mt-2 size-44 rounded-md border bg-white p-2"
          />
          <p className="mt-2 text-muted">
            Ou saisissez la clé :{' '}
            <code className="font-mono text-foreground select-all">{groups(enrollment.secret)}</code>
          </p>
        </li>
        <li>Saisissez le code à 6 chiffres affiché par l’application.</li>
      </ol>
      {failure ? <Alert tone="critical">{failure}</Alert> : null}
      <Field label="Code de vérification" htmlFor="enroll-code" error={errors.code?.message}>
        <Input
          id="enroll-code"
          inputMode="numeric"
          autoComplete="one-time-code"
          maxLength={6}
          className="max-w-40 text-center tracking-[0.4em]"
          {...register('code')}
        />
      </Field>
      <Button type="submit" size="sm" disabled={isSubmitting}>
        {isSubmitting ? 'Vérification…' : 'Activer'}
      </Button>
    </form>
  );
}

/** `requiredBySis`: the active SIS requires it for every access (a new one must follow a removal). */
export function SecondFactorSection({ requiredBySis = false }: { requiredBySis?: boolean }) {
  // Identity-level data: cleared with the rest of the cache when the person changes.
  const factorsQuery = useQuery({ queryKey: ['auth', 'totp-factors'], queryFn: listTotpFactors, retry: false });
  const factors = factorsQuery.data ?? null;
  const [enrollment, setEnrollment] = useState<TotpEnrollment | null>(null);
  const [confirmRemoval, setConfirmRemoval] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [notice, setNotice] = useState<string | null>(null);
  const [actionFailure, setFailure] = useState<string | null>(null);
  const failure = actionFailure ?? (factorsQuery.error ? messageOf(factorsQuery.error) : null);
  const load = async () => {
    await factorsQuery.refetch();
  };

  async function run(action: () => Promise<void>) {
    setBusy(true);
    setFailure(null);
    setNotice(null);
    try {
      await action();
    } catch (error) {
      setFailure(messageOf(error));
    } finally {
      setBusy(false);
    }
  }

  if (factors === null && !failure) return <Skeleton className="h-10 w-full" />;

  return (
    <div className="space-y-4">
      {notice ? <Alert tone="info">{notice}</Alert> : null}
      {failure ? <Alert tone="critical">{failure}</Alert> : null}

      {factors && factors.length > 0 ? (
        <ul className="space-y-3">
          {factors.map((factor) => (
            <li key={factor.id} className="flex flex-wrap items-center justify-between gap-3">
              <div className="flex items-center gap-2">
                <ShieldCheck aria-hidden="true" className="size-5 text-success" />
                <div>
                  <p className="text-sm font-semibold">{factor.friendlyName ?? 'Application d’authentification'}</p>
                  <p className="text-xs text-muted">Activée le {dateFormat.format(new Date(factor.createdAt))}</p>
                </div>
                <Badge tone="success">Active</Badge>
              </div>
              {confirmRemoval === factor.id ? (
                <div className="flex flex-wrap items-center gap-2">
                  <span className="text-sm">
                    {requiredBySis
                      ? 'Votre SIS l’exige : vous devrez en activer une nouvelle avant de continuer. Confirmer ?'
                      : 'Les actions sensibles vous seront refusées. Confirmer ?'}
                  </span>
                  <Button
                    size="sm"
                    variant="danger"
                    disabled={busy}
                    onClick={() =>
                      void run(async () => {
                        await removeTotpFactor(factor.id);
                        setConfirmRemoval(null);
                        setNotice('La double authentification est désactivée.');
                        await load();
                      })
                    }
                  >
                    Retirer
                  </Button>
                  <Button size="sm" variant="ghost" onClick={() => setConfirmRemoval(null)}>
                    Annuler
                  </Button>
                </div>
              ) : (
                <Button size="sm" variant="ghost" onClick={() => setConfirmRemoval(factor.id)}>
                  Retirer
                </Button>
              )}
            </li>
          ))}
        </ul>
      ) : enrollment ? (
        <EnrollmentForm
          enrollment={enrollment}
          onDone={() =>
            void run(async () => {
              setEnrollment(null);
              setNotice('Double authentification activée : votre code vous sera demandé à chaque connexion.');
              await load();
            })
          }
        />
      ) : (
        <div className="space-y-3">
          <p className="text-sm text-muted">
            Un code à usage unique, généré par une application sur votre téléphone, vous sera demandé à chaque connexion
            en plus de votre mot de passe.
          </p>
          <Button
            size="sm"
            disabled={busy}
            onClick={() => void run(async () => setEnrollment(await startTotpEnrollment()))}
          >
            Activer la double authentification
          </Button>
        </div>
      )}
    </div>
  );
}
