import { BASEMAP_MANIFEST_VERSION, isSafeBasemapPath } from '@etare/domain';
import { isoDateTimeSchema, sha256Schema, uuidSchema } from '@etare/schemas';
import { z } from 'zod';

/**
 * Offline base maps of the tablets (CAR-01 to CAR-03, ADR-024): one file per
 * sector, prepared by the worker from the configured source, signed by the
 * publication key and distributed apart from the ETARE publications.
 */
const lonSchema = z.number().min(-180).max(180);
const latSchema = z.number().min(-90).max(90);
const bboxSchema = z.tuple([lonSchema, latSchema, lonSchema, latSchema]);

export const BASEMAP_RIGHTS = ['approved', 'unverified', 'forbidden'] as const;
export const BASEMAP_PACK_STATUSES = ['queued', 'building', 'ready', 'failed', 'superseded'] as const;
export const BASEMAP_REASONS = ['initial', 'coverage', 'source', 'renewal', 'manual'] as const;

/** Product a base map comes from, as the tablet shows it (attribution, licence, test data). */
export const basemapSourceRefSchema = z
  .object({
    id: z.string().regex(/^[a-z0-9-]{1,40}$/),
    product: z.string().min(1).max(120),
    attribution: z.string().min(1).max(200),
    licence_name: z.string().min(1).max(120),
    licence_url: z.url(),
    /** Test data generated by the platform: never a real map. */
    synthetic: z.boolean(),
  })
  .meta({ id: 'BasemapSourceRef' });
export type BasemapSourceRef = z.infer<typeof basemapSourceRefSchema>;

export const basemapFileSchema = z
  .object({
    path: z.string().refine(isSafeBasemapPath, 'Nom de fichier de fond invalide.'),
    sha256: sha256Schema,
    size_bytes: z.number().int().nonnegative(),
    media_type: z.string().min(1).max(100),
    /** Parts of the transfer, in order; their concatenation is the file. */
    parts: z
      .array(z.object({ sha256: sha256Schema, size_bytes: z.number().int().positive() }))
      .min(1)
      .max(64),
  })
  .meta({ id: 'BasemapFile' });
export type BasemapFile = z.infer<typeof basemapFileSchema>;

/** Signed description of a base map: what it covers, where it comes from, its files. */
export const basemapManifestSchema = z
  .object({
    manifest_version: z.literal(BASEMAP_MANIFEST_VERSION),
    kind: z.literal('basemap'),
    pack_id: uuidSchema,
    tenant_id: uuidSchema,
    sector_id: uuidSchema,
    sector_name: z.string(),
    version: z.number().int().positive(),
    source: basemapSourceRefSchema,
    built_at: isoDateTimeSchema,
    renew_after: isoDateTimeSchema,
    coverage: z.object({
      /** General view: the extent of the sites of the sector and a margin. */
      bounds: bboxSchema,
      center: z.tuple([lonSchema, latSchema]),
      general_max_zoom: z.number().int().min(0).max(22),
      detail_max_zoom: z.number().int().min(0).max(22),
      detail_radius_m: z.number().int().positive(),
      /** Distributed sites around which the detail goes up to detail_max_zoom. */
      detail_points: z.array(z.tuple([lonSchema, latSchema])).max(20_000),
    }),
    tiles: z.literal('tiles.pmtiles'),
    style: z.literal('style.json'),
    tile_count: z.number().int().nonnegative(),
    total_bytes: z.number().int().nonnegative(),
    files: z.array(basemapFileSchema).min(2).max(10),
  })
  .meta({ id: 'BasemapManifest' });
export type BasemapManifest = z.infer<typeof basemapManifestSchema>;

/** A base map the terminal must hold (entry of the signed catalogue). */
export const catalogBasemapSchema = z
  .object({
    pack_id: uuidSchema,
    sector_id: uuidSchema,
    sector_name: z.string(),
    version: z.number().int().positive(),
    /** SHA-256 of the canonical JSON of the signed manifest. */
    manifest_hash: sha256Schema,
    total_bytes: z.number().int().nonnegative(),
    built_at: isoDateTimeSchema,
    renew_after: isoDateTimeSchema,
  })
  .meta({ id: 'CatalogBasemap' });
export type CatalogBasemap = z.infer<typeof catalogBasemapSchema>;

// ------------------------------------------------------------------ administration (device:manage)
export const basemapSourceSchema = basemapSourceRefSchema
  .extend({
    /** Offline rights of the product (ADR-024): approved only after the rights sheet is signed off. */
    rights: z.enum(BASEMAP_RIGHTS),
    /** Reference of the rights sheet that approved them. */
    rights_reference: z.string().nullable(),
    /** The platform can prepare base maps with it (approved rights). */
    usable: z.boolean(),
  })
  .meta({ id: 'BasemapSource' });
export type BasemapSource = z.infer<typeof basemapSourceSchema>;

export const basemapPackSummarySchema = z
  .object({
    id: uuidSchema,
    version: z.number().int().positive(),
    status: z.enum(BASEMAP_PACK_STATUSES),
    reason: z.enum(BASEMAP_REASONS),
    source_id: z.string(),
    requested_at: isoDateTimeSchema,
    started_at: isoDateTimeSchema.nullable(),
    built_at: isoDateTimeSchema.nullable(),
    renew_after: isoDateTimeSchema.nullable(),
    total_bytes: z.number().int().nonnegative().nullable(),
    tile_count: z.number().int().nonnegative().nullable(),
    error_code: z.string().nullable(),
    error_detail: z.string().nullable(),
  })
  .meta({ id: 'BasemapPackSummary' });
export type BasemapPackSummary = z.infer<typeof basemapPackSummarySchema>;

export const basemapSectorStateSchema = z
  .object({
    sector: z.object({ id: uuidSchema, name: z.string(), code: z.string().nullable() }),
    /** At least one terminal receives this sector (the base map is prepared only then). */
    eligible: z.boolean(),
    /** Located sites of the sector, and the distributed ones (detail areas). */
    site_count: z.number().int().nonnegative(),
    detail_count: z.number().int().nonnegative(),
    /** File in force on the tablets. */
    current: basemapPackSummarySchema.nullable(),
    /** Newer preparation, queued, running or failed. */
    latest: basemapPackSummarySchema.nullable(),
    /** The sites moved since the file in force: a new one will be prepared. */
    stale: z.boolean(),
    devices: z.object({
      expected: z.number().int().nonnegative(),
      installed: z.number().int().nonnegative(),
    }),
  })
  .meta({ id: 'BasemapSectorState' });
export type BasemapSectorState = z.infer<typeof basemapSectorStateSchema>;

export const basemapOverviewSchema = z
  .object({
    /** Source configured on the platform; null: no base map on this platform. */
    source: basemapSourceSchema.nullable(),
    sectors: z.array(basemapSectorStateSchema),
    /** Base maps of a tablet, all sectors together. */
    device_budget_bytes: z.number().int().positive(),
  })
  .meta({ id: 'BasemapOverview' });
export type BasemapOverview = z.infer<typeof basemapOverviewSchema>;
