import type { z } from 'zod';
import {
  accountSessionListSchema,
  recoveryCodeUseSchema,
  recoveryCodesSchema,
  recoveryCodesStateSchema,
  secondFactorRecoverySchema,
  securitySettingsSchema,
  sessionRevocationSchema,
} from './account';
import { notificationListQuerySchema, notificationListSchema, notificationSchema } from './notifications';
import {
  accessEventListQuerySchema,
  accessEventListSchema,
  syncAccessEventsResultSchema,
  syncAccessEventsSchema,
} from './access-events';
import {
  contributionCreateSchema,
  contributionListQuerySchema,
  contributionListSchema,
  contributionMessageCreateSchema,
  contributionReceiptSchema,
  contributionSchema,
  contributionUpdateSchema,
  contributionUploadedSchema,
  portalContributionListQuerySchema,
  portalContributionListSchema,
  portalContributionSchema,
} from './contributions';
import {
  assetDownloadQuerySchema,
  assetDownloadSchema,
  documentCreateSchema,
  documentListResponseSchema,
  documentSchema,
  documentUpdateSchema,
  documentUploadResponseSchema,
  documentVersionCreateSchema,
  uploadConfirmationSchema,
} from './documents';
import {
  fieldReportListQuerySchema,
  fieldReportListSchema,
  fieldReportReceiptSchema,
  fieldReportSchema,
  fieldReportSubmitSchema,
  fieldReportUpdateSchema,
  fieldReportUploadedSchema,
  syncReportsSchema,
} from './field-reports';
import { addressCandidatesSchema, addressSearchQuerySchema, reverseGeocodingQuerySchema } from './geocoding';
import { mapCatalogSchema, mapSitesQuerySchema, mapSitesResponseSchema } from './map';
import { basemapOverviewSchema } from './basemaps';
import {
  myPortalInvitationListSchema,
  portalAccessSchema,
  portalDocumentParamsSchema,
  portalInvitationAcceptedSchema,
  portalInvitationCreateSchema,
  portalInvitationCreatedSchema,
  portalInvitationListSchema,
  portalInvitationRevokeSchema,
  portalInvitationSchema,
  portalSettingsSchema,
  portalSiteListSchema,
  portalSiteSchema,
} from './portal';
import {
  mapFeaturesQuerySchema,
  mapFeaturesResponseSchema,
  objectPhotoCreateSchema,
  objectPhotoSchema,
  objectPhotoUpdateSchema,
  objectPhotoUploadSchema,
  objectTypeListSchema,
  operationalObjectCreateSchema,
  operationalObjectListSchema,
  operationalObjectSchema,
  operationalObjectUpdateSchema,
} from './objects';
import {
  planCreateSchema,
  planListResponseSchema,
  planRevisionCreateSchema,
  planSchema,
  planUpdateSchema,
  planUploadResponseSchema,
  zoneCreateSchema,
  zoneListResponseSchema,
  zoneSchema,
  zoneUpdateSchema,
} from './plans';
import {
  etareDossierListQuerySchema,
  etareLayoutSettingsSchema,
  publicationSummarySchema,
  publicationWithdrawSchema,
  etareDossierListSchema,
  etareOverviewSchema,
  etarePreviewSchema,
  etareRevisionSchema,
  revisionCreateSchema,
  revisionDecisionSchema,
  revisionDetailSchema,
  revisionSubmitSchema,
  validationQueueSchema,
} from './etare';
import {
  riskCreateSchema,
  riskListSchema,
  riskSchema,
  riskTypeCreateSchema,
  riskTypeListQuerySchema,
  riskTypeListSchema,
  riskTypeSchema,
  riskTypeUpdateSchema,
  riskUpdateSchema,
} from './risks';
import {
  memberInvitationSchema,
  memberInviteSchema,
  memberListResponseSchema,
  memberSchema,
  memberSensitiveAccessSchema,
  memberUpdateSchema,
} from './members';
import {
  devicePerimeterSchema,
  memberPerimeterSchema,
  sectorCommuneListSchema,
  sectorListSchema,
  sectorSaveSchema,
  sectorSchema,
} from './sectors';
import {
  buildingCreateSchema,
  buildingListResponseSchema,
  buildingSchema,
  buildingUpdateSchema,
  classificationCreateSchema,
  classificationListResponseSchema,
  classificationSchema,
  classificationUpdateSchema,
  contactCreateSchema,
  contactListResponseSchema,
  contactSchema,
  contactUpdateSchema,
  externalIdCreateSchema,
  externalIdListResponseSchema,
  externalIdSchema,
  idParamsSchema,
  levelCreateSchema,
  levelSchema,
  levelUpdateSchema,
  siteCreateSchema,
  siteArchiveSchema,
  siteUpdateSchema,
} from './referential';
import {
  healthResponseSchema,
  meResponseSchema,
  siteDetailSchema,
  siteListQuerySchema,
  siteListResponseSchema,
} from './resources';
import {
  deviceCreateSchema,
  deviceEnrollSchema,
  deviceEnrollmentCodeSchema,
  deviceEnrollmentSchema,
  deviceKeyRotateSchema,
  deviceKeyRotationSchema,
  deviceListSchema,
  deviceRevokeSchema,
  deviceSchema,
  signedCatalogSchema,
  terminalPolicySchema,
  signedKeysetSchema,
  syncBasemapReceiptResultSchema,
  syncBasemapReceiptSchema,
  syncBasemapSchema,
  syncDownloadRequestSchema,
  syncDownloadsSchema,
  syncPackageSchema,
  syncReceiptResultSchema,
  syncReceiptSchema,
} from './sync';
import { tenantSupervisionSchema } from './supervision';

export const API_VERSION = 'v1';
export const API_BASE_PATH = `/api/${API_VERSION}`;

/**
 * Framework-agnostic description of an endpoint. The same objects drive the
 * OpenAPI document, the server-side validation (services/api) and the typed
 * clients, so they cannot drift apart silently.
 */
export interface EndpointContract {
  readonly operationId: string;
  readonly method: 'get' | 'post' | 'patch' | 'put' | 'delete';
  /** OpenAPI path template relative to API_BASE_PATH, e.g. /sites/{id}. */
  readonly path: string;
  readonly summary: string;
  readonly tags: readonly string[];
  /** 'user': a valid access token is required. */
  readonly auth: 'public' | 'user';
  /** true: the X-Tenant-Id header (active SIS) is required. */
  readonly tenantScoped: boolean;
  readonly params?: z.ZodObject;
  readonly query?: z.ZodObject;
  /** JSON request body. */
  readonly body?: z.ZodType;
  /**
   * Optimistic concurrency. 'etag': the response carries an ETag (row version).
   * 'if-match': the request must carry If-Match (428 otherwise, 412 if stale).
   */
  readonly concurrency?: 'etag' | 'if-match';
  /** true: the request must be signed by an enrolled terminal (X-Device-Id, X-Device-Time, X-Device-Signature). */
  readonly deviceProof?: boolean;
  readonly successStatus: 200 | 201 | 202;
  readonly response: z.ZodType;
}

/** Shorthand for the many tenant-scoped, authenticated endpoints. */
function tenantEndpoint<const E extends Omit<EndpointContract, 'auth' | 'tenantScoped'>>(endpoint: E) {
  return { ...endpoint, auth: 'user', tenantScoped: true } as const;
}

export const endpoints = {
  getHealth: {
    operationId: 'getHealth',
    method: 'get',
    path: '/health',
    summary: 'État du service',
    tags: ['system'],
    auth: 'public',
    tenantScoped: false,
    successStatus: 200,
    response: healthResponseSchema,
  },
  getMe: {
    operationId: 'getMe',
    method: 'get',
    path: '/me',
    summary: 'Utilisateur connecté et SIS auxquels il appartient',
    tags: ['identity'],
    auth: 'user',
    tenantScoped: false,
    successStatus: 200,
    response: meResponseSchema,
  },
  listMySessions: {
    operationId: 'listMySessions',
    method: 'get',
    path: '/me/sessions',
    summary: 'Sessions ouvertes du compte (navigateurs, applications)',
    tags: ['identity'],
    auth: 'user',
    tenantScoped: false,
    successStatus: 200,
    response: accountSessionListSchema,
  },
  revokeMySession: {
    operationId: 'revokeMySession',
    method: 'post',
    path: '/me/sessions/{id}/revocation',
    summary: 'Fermer une session du compte (effet à la requête suivante)',
    tags: ['identity'],
    auth: 'user',
    tenantScoped: false,
    params: idParamsSchema,
    successStatus: 200,
    response: sessionRevocationSchema,
  },
  getMyRecoveryCodes: {
    operationId: 'getMyRecoveryCodes',
    method: 'get',
    path: '/me/recovery-codes',
    summary: 'Codes de secours restants (jamais les codes eux-mêmes)',
    tags: ['identity'],
    auth: 'user',
    tenantScoped: false,
    successStatus: 200,
    response: recoveryCodesStateSchema,
  },
  regenerateMyRecoveryCodes: {
    operationId: 'regenerateMyRecoveryCodes',
    method: 'post',
    path: '/me/recovery-codes',
    summary: 'Générer dix nouveaux codes de secours (second facteur en cours d’usage) ; les anciens ne valent plus',
    tags: ['identity'],
    auth: 'user',
    tenantScoped: false,
    successStatus: 201,
    response: recoveryCodesSchema,
  },
  recoverSecondFactor: {
    operationId: 'recoverSecondFactor',
    method: 'post',
    path: '/me/second-factor/recovery',
    summary:
      'Remplacer un second facteur perdu par un code de secours : facteur retiré, autres sessions fermées, alerte',
    tags: ['identity'],
    auth: 'user',
    tenantScoped: false,
    body: recoveryCodeUseSchema,
    successStatus: 200,
    response: secondFactorRecoverySchema,
  },
  revokeMyOtherSessions: {
    operationId: 'revokeMyOtherSessions',
    method: 'post',
    path: '/me/sessions/revocation',
    summary: 'Fermer toutes les autres sessions du compte',
    tags: ['identity'],
    auth: 'user',
    tenantScoped: false,
    successStatus: 200,
    response: sessionRevocationSchema,
  },

  // ---------------------------------------------------------------- map
  getMapCatalog: {
    operationId: 'getMapCatalog',
    method: 'get',
    path: '/map/sources',
    summary: 'Fonds de carte autorisés (catalogue serveur : URL, zooms, attribution, droits)',
    tags: ['map'],
    auth: 'user',
    tenantScoped: false,
    successStatus: 200,
    response: mapCatalogSchema,
  },
  listMapSites: tenantEndpoint({
    operationId: 'listMapSites',
    method: 'get',
    path: '/map/sites',
    summary: 'Sites positionnés du SIS actif en GeoJSON, filtrables et limités à l’emprise visible',
    tags: ['map'],
    query: mapSitesQuerySchema,
    successStatus: 200,
    response: mapSitesResponseSchema,
  }),

  listMapFeatures: tenantEndpoint({
    operationId: 'listMapFeatures',
    method: 'get',
    path: '/map/features',
    summary: 'Emprises des bâtiments et points opérationnels d’une zone restreinte (vue rapprochée)',
    tags: ['map'],
    query: mapFeaturesQuerySchema,
    successStatus: 200,
    response: mapFeaturesResponseSchema,
  }),
  searchAddresses: tenantEndpoint({
    operationId: 'searchAddresses',
    method: 'get',
    path: '/geocoding/search',
    summary: 'Rechercher une adresse (géocodeur IGN, appelé par le serveur)',
    tags: ['map'],
    query: addressSearchQuerySchema,
    successStatus: 200,
    response: addressCandidatesSchema,
  }),
  reverseGeocode: tenantEndpoint({
    operationId: 'reverseGeocode',
    method: 'get',
    path: '/geocoding/reverse',
    summary: 'Adresse la plus proche d’un point (géocodeur IGN, appelé par le serveur)',
    tags: ['map'],
    query: reverseGeocodingQuerySchema,
    successStatus: 200,
    response: addressCandidatesSchema,
  }),

  // ---------------------------------------------------------------- sites
  listSites: tenantEndpoint({
    operationId: 'listSites',
    method: 'get',
    path: '/sites',
    summary: 'Rechercher les sites du SIS actif (données de travail)',
    tags: ['sites'],
    query: siteListQuerySchema,
    successStatus: 200,
    response: siteListResponseSchema,
  }),
  createSite: tenantEndpoint({
    operationId: 'createSite',
    method: 'post',
    path: '/sites',
    summary: 'Créer un site',
    tags: ['sites'],
    body: siteCreateSchema,
    concurrency: 'etag',
    successStatus: 201,
    response: siteDetailSchema,
  }),
  getSite: tenantEndpoint({
    operationId: 'getSite',
    method: 'get',
    path: '/sites/{id}',
    summary: 'Détail d’un site du SIS actif',
    tags: ['sites'],
    params: idParamsSchema,
    concurrency: 'etag',
    successStatus: 200,
    response: siteDetailSchema,
  }),
  updateSite: tenantEndpoint({
    operationId: 'updateSite',
    method: 'patch',
    path: '/sites/{id}',
    summary: 'Modifier un site',
    tags: ['sites'],
    params: idParamsSchema,
    body: siteUpdateSchema,
    concurrency: 'if-match',
    successStatus: 200,
    response: siteDetailSchema,
  }),

  // ---------------------------------------------------------------- buildings and levels
  listBuildings: tenantEndpoint({
    operationId: 'listBuildings',
    method: 'get',
    path: '/sites/{id}/buildings',
    summary: 'Bâtiments et niveaux d’un site',
    tags: ['buildings'],
    params: idParamsSchema,
    successStatus: 200,
    response: buildingListResponseSchema,
  }),
  createBuilding: tenantEndpoint({
    operationId: 'createBuilding',
    method: 'post',
    path: '/sites/{id}/buildings',
    summary: 'Ajouter un bâtiment à un site',
    tags: ['buildings'],
    params: idParamsSchema,
    body: buildingCreateSchema,
    concurrency: 'etag',
    successStatus: 201,
    response: buildingSchema,
  }),
  updateBuilding: tenantEndpoint({
    operationId: 'updateBuilding',
    method: 'patch',
    path: '/buildings/{id}',
    summary: 'Modifier un bâtiment',
    tags: ['buildings'],
    params: idParamsSchema,
    body: buildingUpdateSchema,
    concurrency: 'if-match',
    successStatus: 200,
    response: buildingSchema,
  }),
  createLevel: tenantEndpoint({
    operationId: 'createLevel',
    method: 'post',
    path: '/buildings/{id}/levels',
    summary: 'Ajouter un niveau à un bâtiment',
    tags: ['buildings'],
    params: idParamsSchema,
    body: levelCreateSchema,
    concurrency: 'etag',
    successStatus: 201,
    response: levelSchema,
  }),
  updateLevel: tenantEndpoint({
    operationId: 'updateLevel',
    method: 'patch',
    path: '/levels/{id}',
    summary: 'Modifier un niveau',
    tags: ['buildings'],
    params: idParamsSchema,
    body: levelUpdateSchema,
    concurrency: 'if-match',
    successStatus: 200,
    response: levelSchema,
  }),

  // ---------------------------------------------------------------- classifications
  listClassifications: tenantEndpoint({
    operationId: 'listClassifications',
    method: 'get',
    path: '/sites/{id}/classifications',
    summary: 'Classifications réglementaires d’un site (ERP, IGH, ICPE...)',
    tags: ['classifications'],
    params: idParamsSchema,
    successStatus: 200,
    response: classificationListResponseSchema,
  }),
  createClassification: tenantEndpoint({
    operationId: 'createClassification',
    method: 'post',
    path: '/sites/{id}/classifications',
    summary: 'Ajouter une classification datée',
    tags: ['classifications'],
    params: idParamsSchema,
    body: classificationCreateSchema,
    concurrency: 'etag',
    successStatus: 201,
    response: classificationSchema,
  }),
  updateClassification: tenantEndpoint({
    operationId: 'updateClassification',
    method: 'patch',
    path: '/classifications/{id}',
    summary: 'Modifier ou clore une classification',
    tags: ['classifications'],
    params: idParamsSchema,
    body: classificationUpdateSchema,
    concurrency: 'if-match',
    successStatus: 200,
    response: classificationSchema,
  }),

  // ---------------------------------------------------------------- contacts
  listContacts: tenantEndpoint({
    operationId: 'listContacts',
    method: 'get',
    path: '/sites/{id}/contacts',
    summary: 'Contacts et astreintes d’un site',
    tags: ['contacts'],
    params: idParamsSchema,
    successStatus: 200,
    response: contactListResponseSchema,
  }),
  createContact: tenantEndpoint({
    operationId: 'createContact',
    method: 'post',
    path: '/sites/{id}/contacts',
    summary: 'Ajouter un contact',
    tags: ['contacts'],
    params: idParamsSchema,
    body: contactCreateSchema,
    concurrency: 'etag',
    successStatus: 201,
    response: contactSchema,
  }),
  updateContact: tenantEndpoint({
    operationId: 'updateContact',
    method: 'patch',
    path: '/contacts/{id}',
    summary: 'Modifier, vérifier ou archiver un contact',
    tags: ['contacts'],
    params: idParamsSchema,
    body: contactUpdateSchema,
    concurrency: 'if-match',
    successStatus: 200,
    response: contactSchema,
  }),

  // ---------------------------------------------------------------- external identifiers
  listExternalIds: tenantEndpoint({
    operationId: 'listExternalIds',
    method: 'get',
    path: '/sites/{id}/external-ids',
    summary: 'Identifiants externes (SIG, SGO, DECI...) du site et de ses éléments',
    tags: ['sites'],
    params: idParamsSchema,
    successStatus: 200,
    response: externalIdListResponseSchema,
  }),
  createExternalId: tenantEndpoint({
    operationId: 'createExternalId',
    method: 'post',
    path: '/sites/{id}/external-ids',
    summary: 'Associer un identifiant externe',
    tags: ['sites'],
    params: idParamsSchema,
    body: externalIdCreateSchema,
    successStatus: 201,
    response: externalIdSchema,
  }),

  // ---------------------------------------------------------------- operational objects
  listObjectTypes: tenantEndpoint({
    operationId: 'listObjectTypes',
    method: 'get',
    path: '/object-types',
    summary: 'Catalogue des types d’objets opérationnels (global et propre au SIS)',
    tags: ['objects'],
    successStatus: 200,
    response: objectTypeListSchema,
  }),
  listSiteObjects: tenantEndpoint({
    operationId: 'listSiteObjects',
    method: 'get',
    path: '/sites/{id}/objects',
    summary: 'Points opérationnels d’un site (accès, eau, coupures…)',
    tags: ['objects'],
    params: idParamsSchema,
    successStatus: 200,
    response: operationalObjectListSchema,
  }),
  createSiteObject: tenantEndpoint({
    operationId: 'createSiteObject',
    method: 'post',
    path: '/sites/{id}/objects',
    summary: 'Placer un point opérationnel sur la carte et/ou sur un plan',
    tags: ['objects'],
    params: idParamsSchema,
    body: operationalObjectCreateSchema,
    successStatus: 201,
    response: operationalObjectSchema,
  }),
  updateObject: tenantEndpoint({
    operationId: 'updateObject',
    method: 'patch',
    path: '/objects/{id}',
    summary: 'Modifier, déplacer, vérifier ou archiver un point opérationnel',
    tags: ['objects'],
    params: idParamsSchema,
    body: operationalObjectUpdateSchema,
    concurrency: 'if-match',
    successStatus: 200,
    response: operationalObjectSchema,
  }),
  createObjectPhoto: tenantEndpoint({
    operationId: 'createObjectPhoto',
    method: 'post',
    path: '/objects/{id}/photos',
    summary: 'Ajouter une photo à un point (PLAN-05) : URL de dépôt, contrôle par le worker avant toute diffusion',
    tags: ['objects'],
    params: idParamsSchema,
    body: objectPhotoCreateSchema,
    successStatus: 201,
    response: objectPhotoUploadSchema,
  }),
  updateObjectPhoto: tenantEndpoint({
    operationId: 'updateObjectPhoto',
    method: 'patch',
    path: '/object-photos/{id}',
    summary: 'Modifier la légende d’une photo ou l’archiver (jamais supprimée)',
    tags: ['objects'],
    params: idParamsSchema,
    body: objectPhotoUpdateSchema,
    concurrency: 'if-match',
    successStatus: 200,
    response: objectPhotoSchema,
  }),

  // ---------------------------------------------------------------- plans
  listSitePlans: tenantEndpoint({
    operationId: 'listSitePlans',
    method: 'get',
    path: '/sites/{id}/plans',
    summary: 'Plans d’un site (masse, niveaux, réseaux, évacuation) et leurs révisions de fond',
    tags: ['plans'],
    params: idParamsSchema,
    successStatus: 200,
    response: planListResponseSchema,
  }),
  createPlan: tenantEndpoint({
    operationId: 'createPlan',
    method: 'post',
    path: '/sites/{id}/plans',
    summary: 'Créer un plan et obtenir l’URL de dépôt de son fond (quarantaine)',
    tags: ['plans'],
    params: idParamsSchema,
    body: planCreateSchema,
    successStatus: 201,
    response: planUploadResponseSchema,
  }),
  updatePlan: tenantEndpoint({
    operationId: 'updatePlan',
    method: 'patch',
    path: '/plans/{id}',
    summary: 'Renommer ou archiver un plan',
    tags: ['plans'],
    params: idParamsSchema,
    body: planUpdateSchema,
    concurrency: 'if-match',
    successStatus: 200,
    response: planSchema,
  }),
  createPlanRevision: tenantEndpoint({
    operationId: 'createPlanRevision',
    method: 'post',
    path: '/plans/{id}/revisions',
    summary: 'Remplacer le fond d’un plan (nouvelle révision, les précédentes sont conservées)',
    tags: ['plans'],
    params: idParamsSchema,
    body: planRevisionCreateSchema,
    successStatus: 201,
    response: planUploadResponseSchema,
  }),
  listSiteZones: tenantEndpoint({
    operationId: 'listSiteZones',
    method: 'get',
    path: '/sites/{id}/zones',
    summary: 'Zones des niveaux d’un site (locaux, refuges, circulations…) dessinées sur les plans',
    tags: ['plans'],
    params: idParamsSchema,
    successStatus: 200,
    response: zoneListResponseSchema,
  }),
  createZone: tenantEndpoint({
    operationId: 'createZone',
    method: 'post',
    path: '/sites/{id}/zones',
    summary: 'Dessiner une zone sur le fond actuel d’un plan de niveau',
    tags: ['plans'],
    params: idParamsSchema,
    body: zoneCreateSchema,
    successStatus: 201,
    response: zoneSchema,
  }),
  updateZone: tenantEndpoint({
    operationId: 'updateZone',
    method: 'patch',
    path: '/zones/{id}',
    summary: 'Renommer, redessiner ou archiver une zone',
    tags: ['plans'],
    params: idParamsSchema,
    body: zoneUpdateSchema,
    concurrency: 'if-match',
    successStatus: 200,
    response: zoneSchema,
  }),

  // ---------------------------------------------------------------- risks
  listRiskTypes: tenantEndpoint({
    operationId: 'listRiskTypes',
    method: 'get',
    path: '/risk-types',
    summary: 'Catalogue des types de risques (national et propre au SIS)',
    tags: ['risks'],
    query: riskTypeListQuerySchema,
    successStatus: 200,
    response: riskTypeListSchema,
  }),
  createRiskType: tenantEndpoint({
    operationId: 'createRiskType',
    method: 'post',
    path: '/risk-types',
    summary: 'Ajouter un type de risque propre au SIS, avec ses champs',
    tags: ['risks'],
    body: riskTypeCreateSchema,
    successStatus: 201,
    response: riskTypeSchema,
  }),
  updateRiskType: tenantEndpoint({
    operationId: 'updateRiskType',
    method: 'patch',
    path: '/risk-types/{id}',
    summary: 'Modifier ou retirer un type de risque propre au SIS',
    tags: ['risks'],
    params: idParamsSchema,
    body: riskTypeUpdateSchema,
    concurrency: 'if-match',
    successStatus: 200,
    response: riskTypeSchema,
  }),
  listSiteRisks: tenantEndpoint({
    operationId: 'listSiteRisks',
    method: 'get',
    path: '/sites/{id}/risks',
    summary: 'Risques d’un site, leur portée (site, bâtiment, niveau, zone) et leur position sur les plans',
    tags: ['risks'],
    params: idParamsSchema,
    successStatus: 200,
    response: riskListSchema,
  }),
  createSiteRisk: tenantEndpoint({
    operationId: 'createSiteRisk',
    method: 'post',
    path: '/sites/{id}/risks',
    summary: 'Localiser un risque sur un site, un bâtiment, un niveau, une zone ou un plan',
    tags: ['risks'],
    params: idParamsSchema,
    body: riskCreateSchema,
    successStatus: 201,
    response: riskSchema,
  }),
  updateRisk: tenantEndpoint({
    operationId: 'updateRisk',
    method: 'patch',
    path: '/risks/{id}',
    summary: 'Modifier, déplacer ou archiver un risque',
    tags: ['risks'],
    params: idParamsSchema,
    body: riskUpdateSchema,
    concurrency: 'if-match',
    successStatus: 200,
    response: riskSchema,
  }),

  // ---------------------------------------------------------------- ETARE workflow
  listEtareDossiers: tenantEndpoint({
    operationId: 'listEtareDossiers',
    method: 'get',
    path: '/etare',
    summary: 'Dossiers ETARE du SIS : version publiée et révision en cours de chaque site, avec compteurs exacts',
    tags: ['etare'],
    query: etareDossierListQuerySchema,
    successStatus: 200,
    response: etareDossierListSchema,
  }),
  getSiteEtare: tenantEndpoint({
    operationId: 'getSiteEtare',
    method: 'get',
    path: '/sites/{id}/etare',
    summary: 'Dossier ETARE d’un site : révisions, décisions et publications',
    tags: ['etare'],
    params: idParamsSchema,
    successStatus: 200,
    response: etareOverviewSchema,
  }),
  previewSiteEtare: tenantEndpoint({
    operationId: 'previewSiteEtare',
    method: 'get',
    path: '/sites/{id}/etare/preview',
    summary: 'Aperçu de la version qui serait soumise et contrôles avant soumission',
    tags: ['etare'],
    params: idParamsSchema,
    successStatus: 200,
    response: etarePreviewSchema,
  }),
  createRevision: tenantEndpoint({
    operationId: 'createRevision',
    method: 'post',
    path: '/sites/{id}/etare/revisions',
    summary: 'Ouvrir une révision (brouillon) du dossier ETARE',
    tags: ['etare'],
    params: idParamsSchema,
    body: revisionCreateSchema,
    successStatus: 201,
    response: etareRevisionSchema,
  }),
  submitRevision: tenantEndpoint({
    operationId: 'submitRevision',
    method: 'post',
    path: '/etare-revisions/{id}/submit',
    summary: 'Soumettre à validation : les données de travail sont figées (instantané canonique et SHA-256)',
    tags: ['etare'],
    params: idParamsSchema,
    body: revisionSubmitSchema,
    concurrency: 'if-match',
    successStatus: 200,
    response: etareRevisionSchema,
  }),
  listValidations: tenantEndpoint({
    operationId: 'listValidations',
    method: 'get',
    path: '/validations',
    summary: 'Révisions en attente de validation dans le SIS',
    tags: ['etare'],
    successStatus: 200,
    response: validationQueueSchema,
  }),
  getRevision: tenantEndpoint({
    operationId: 'getRevision',
    method: 'get',
    path: '/etare-revisions/{id}',
    summary: 'Révision soumise : contenu figé, changements depuis la version publiée, contributeurs',
    tags: ['etare'],
    params: idParamsSchema,
    successStatus: 200,
    response: revisionDetailSchema,
  }),
  decideRevision: tenantEndpoint({
    operationId: 'decideRevision',
    method: 'post',
    path: '/etare-revisions/{id}/decision',
    summary: 'Valider (et publier) ou demander une correction motivée — double authentification',
    tags: ['etare'],
    params: idParamsSchema,
    body: revisionDecisionSchema,
    successStatus: 200,
    response: etareRevisionSchema,
  }),
  getPublicationPdf: tenantEndpoint({
    operationId: 'getPublicationPdf',
    method: 'get',
    path: '/publications/{id}/pdf',
    summary: 'PDF ETARE d’une version publiée : URL signée de 60 s, accès tracé',
    tags: ['etare'],
    params: idParamsSchema,
    successStatus: 200,
    response: assetDownloadSchema,
  }),
  withdrawPublication: tenantEndpoint({
    operationId: 'withdrawPublication',
    method: 'post',
    path: '/publications/{id}/withdrawal',
    summary: 'Retirer la version en vigueur d’un site (validateur, second facteur, motif) : retirée des tablettes',
    tags: ['etare'],
    params: idParamsSchema,
    body: publicationWithdrawSchema,
    concurrency: 'if-match',
    successStatus: 200,
    response: publicationSummarySchema,
  }),
  archiveSite: tenantEndpoint({
    operationId: 'archiveSite',
    method: 'post',
    path: '/sites/{id}/archive',
    summary: 'Archiver un site et son dossier (motif ; aucune version en vigueur ni décision en attente)',
    tags: ['sites'],
    params: idParamsSchema,
    body: siteArchiveSchema,
    concurrency: 'if-match',
    successStatus: 200,
    response: siteDetailSchema,
  }),
  restoreSite: tenantEndpoint({
    operationId: 'restoreSite',
    method: 'post',
    path: '/sites/{id}/restore',
    summary: 'Restaurer un site archivé et son dossier',
    tags: ['sites'],
    params: idParamsSchema,
    concurrency: 'if-match',
    successStatus: 200,
    response: siteDetailSchema,
  }),
  publishRevision: tenantEndpoint({
    operationId: 'publishRevision',
    method: 'post',
    path: '/etare-revisions/{id}/publication',
    summary: 'Relancer la publication d’une révision validée (après un échec de fabrication)',
    tags: ['etare'],
    params: idParamsSchema,
    successStatus: 202,
    response: etareRevisionSchema,
  }),

  // ---------------------------------------------------------------- documents and files
  listDocuments: tenantEndpoint({
    operationId: 'listDocuments',
    method: 'get',
    path: '/sites/{id}/documents',
    summary: 'Documents d’un site et état de contrôle de leurs fichiers',
    tags: ['documents'],
    params: idParamsSchema,
    successStatus: 200,
    response: documentListResponseSchema,
  }),
  createDocument: tenantEndpoint({
    operationId: 'createDocument',
    method: 'post',
    path: '/sites/{id}/documents',
    summary: 'Créer un document et obtenir l’URL de dépôt de son fichier (quarantaine)',
    tags: ['documents'],
    params: idParamsSchema,
    body: documentCreateSchema,
    successStatus: 201,
    response: documentUploadResponseSchema,
  }),
  updateDocument: tenantEndpoint({
    operationId: 'updateDocument',
    method: 'patch',
    path: '/documents/{id}',
    summary: 'Modifier ou archiver un document',
    tags: ['documents'],
    params: idParamsSchema,
    body: documentUpdateSchema,
    concurrency: 'if-match',
    successStatus: 200,
    response: documentSchema,
  }),
  createDocumentVersion: tenantEndpoint({
    operationId: 'createDocumentVersion',
    method: 'post',
    path: '/documents/{id}/versions',
    summary: 'Ajouter une nouvelle version (les précédentes sont conservées)',
    tags: ['documents'],
    params: idParamsSchema,
    body: documentVersionCreateSchema,
    successStatus: 201,
    response: documentUploadResponseSchema,
  }),
  confirmUpload: tenantEndpoint({
    operationId: 'confirmUpload',
    method: 'post',
    path: '/assets/{id}/uploaded',
    summary: 'Signaler la fin du dépôt : le contrôle du fichier est planifié',
    tags: ['documents'],
    params: idParamsSchema,
    successStatus: 202,
    response: uploadConfirmationSchema,
  }),
  getAssetDownload: tenantEndpoint({
    operationId: 'getAssetDownload',
    method: 'get',
    path: '/assets/{id}/download',
    summary: 'URL de téléchargement de courte durée d’un fichier contrôlé ou de sa version réduite (accès tracé)',
    tags: ['documents'],
    params: idParamsSchema,
    query: assetDownloadQuerySchema,
    successStatus: 200,
    response: assetDownloadSchema,
  }),

  // ---------------------------------------------------------------- members of the SIS
  listMembers: tenantEndpoint({
    operationId: 'listMembers',
    method: 'get',
    path: '/members',
    summary: 'Membres du SIS et leurs rôles (administration, double authentification exigée)',
    tags: ['members'],
    successStatus: 200,
    response: memberListResponseSchema,
  }),
  inviteMember: tenantEndpoint({
    operationId: 'inviteMember',
    method: 'post',
    path: '/members',
    summary: 'Inviter une personne dans le SIS (ou rattacher un compte existant)',
    tags: ['members'],
    body: memberInviteSchema,
    successStatus: 201,
    response: memberInvitationSchema,
  }),
  updateMember: tenantEndpoint({
    operationId: 'updateMember',
    method: 'patch',
    path: '/members/{id}',
    summary: 'Modifier les rôles d’un membre, le suspendre ou le réactiver (jamais soi-même)',
    tags: ['members'],
    params: idParamsSchema,
    body: memberUpdateSchema,
    concurrency: 'if-match',
    successStatus: 200,
    response: memberSchema,
  }),

  setMemberPerimeter: tenantEndpoint({
    operationId: 'setMemberPerimeter',
    method: 'put',
    path: '/members/{id}/perimeter',
    summary: 'Limiter les rôles d’un membre à des secteurs ou des sites, ou les rendre au SIS entier (PER-01)',
    tags: ['members'],
    params: idParamsSchema,
    body: memberPerimeterSchema,
    concurrency: 'if-match',
    successStatus: 200,
    response: memberSchema,
  }),

  setMemberSensitiveAccess: tenantEndpoint({
    operationId: 'setMemberSensitiveAccess',
    method: 'put',
    path: '/members/{id}/sensitive-access',
    summary:
      'Habiliter un membre aux sites sensibles « restreints » (12 mois au plus, SIS ou secteurs) ou retirer l’habilitation',
    tags: ['members'],
    params: idParamsSchema,
    body: memberSensitiveAccessSchema,
    concurrency: 'if-match',
    successStatus: 200,
    response: memberSchema,
  }),

  listAccessEvents: tenantEndpoint({
    operationId: 'listAccessEvents',
    method: 'get',
    path: '/access-events',
    summary: 'Journal des consultations, exports et téléchargements des sites sensibles (audit:read)',
    tags: ['audit'],
    query: accessEventListQuerySchema,
    successStatus: 200,
    response: accessEventListSchema,
  }),

  // ---------------------------------------------------------------- sectors (PER-01)
  listSectors: tenantEndpoint({
    operationId: 'listSectors',
    method: 'get',
    path: '/sectors',
    summary: 'Secteurs du SIS : communes, sites ajoutés, membres et terminaux affectés (administration)',
    tags: ['sectors'],
    successStatus: 200,
    response: sectorListSchema,
  }),
  listSectorCommunes: tenantEndpoint({
    operationId: 'listSectorCommunes',
    method: 'get',
    path: '/sectors/communes',
    summary: 'Communes des sites du SIS, pour composer les secteurs',
    tags: ['sectors'],
    successStatus: 200,
    response: sectorCommuneListSchema,
  }),
  createSector: tenantEndpoint({
    operationId: 'createSector',
    method: 'post',
    path: '/sectors',
    summary: 'Créer un secteur : communes (sites futurs compris) et sites ajoutés un à un',
    tags: ['sectors'],
    body: sectorSaveSchema,
    successStatus: 201,
    response: sectorSchema,
  }),
  updateSector: tenantEndpoint({
    operationId: 'updateSector',
    method: 'put',
    path: '/sectors/{id}',
    summary: 'Modifier un secteur ; les tablettes et membres concernés suivent au prochain contact',
    tags: ['sectors'],
    params: idParamsSchema,
    body: sectorSaveSchema,
    concurrency: 'if-match',
    successStatus: 200,
    response: sectorSchema,
  }),
  archiveSector: tenantEndpoint({
    operationId: 'archiveSector',
    method: 'post',
    path: '/sectors/{id}/archive',
    summary: 'Archiver un secteur que plus aucun membre ni terminal n’utilise ; renvoie les secteurs restants',
    tags: ['sectors'],
    params: idParamsSchema,
    concurrency: 'if-match',
    successStatus: 200,
    response: sectorListSchema,
  }),

  getBasemapOverview: tenantEndpoint({
    operationId: 'getBasemapOverview',
    method: 'get',
    path: '/basemaps',
    summary: 'Fonds de carte hors ligne des tablettes : source, droits et état secteur par secteur',
    tags: ['basemaps'],
    successStatus: 200,
    response: basemapOverviewSchema,
  }),
  requestBasemapBuild: tenantEndpoint({
    operationId: 'requestBasemapBuild',
    method: 'post',
    path: '/basemaps/sectors/{id}/builds',
    summary: 'Préparer maintenant le fond de carte d’un secteur (une préparation en cours est conservée)',
    tags: ['basemaps'],
    params: idParamsSchema,
    successStatus: 200,
    response: basemapOverviewSchema,
  }),

  resetMemberSecondFactor: tenantEndpoint({
    operationId: 'resetMemberSecondFactor',
    method: 'post',
    path: '/members/{id}/second-factor-reset',
    summary: 'Réinitialiser le second facteur d’un membre (jamais soi-même, jamais un membre d’un autre SIS)',
    tags: ['members'],
    params: idParamsSchema,
    concurrency: 'if-match',
    successStatus: 200,
    response: memberSchema,
  }),
  getSecuritySettings: tenantEndpoint({
    operationId: 'getSecuritySettings',
    method: 'get',
    path: '/settings/security',
    summary: 'Politique de second facteur du SIS (administration)',
    tags: ['members'],
    successStatus: 200,
    response: securitySettingsSchema,
  }),
  updateSecuritySettings: tenantEndpoint({
    operationId: 'updateSecuritySettings',
    method: 'put',
    path: '/settings/security',
    summary: 'Modifier la politique de second facteur du SIS (second facteur exigé, audité)',
    tags: ['members'],
    body: securitySettingsSchema,
    successStatus: 200,
    response: securitySettingsSchema,
  }),

  // ---------------------------------------------------------------- terminals and offline distribution
  listDevices: tenantEndpoint({
    operationId: 'listDevices',
    method: 'get',
    path: '/devices',
    summary: 'Terminaux du SIS, état de synchronisation et version installée (administration)',
    tags: ['devices'],
    successStatus: 200,
    response: deviceListSchema,
  }),
  createDevice: tenantEndpoint({
    operationId: 'createDevice',
    method: 'post',
    path: '/devices',
    summary: 'Déclarer un terminal : code d’enrôlement à usage unique, valable 24 h, affiché une seule fois',
    tags: ['devices'],
    body: deviceCreateSchema,
    successStatus: 201,
    response: deviceEnrollmentCodeSchema,
  }),
  renewDeviceEnrollment: tenantEndpoint({
    operationId: 'renewDeviceEnrollment',
    method: 'post',
    path: '/devices/{id}/enrollment-code',
    summary: 'Nouveau code d’enrôlement pour un terminal pas encore enrôlé (l’ancien ne vaut plus)',
    tags: ['devices'],
    params: idParamsSchema,
    concurrency: 'if-match',
    successStatus: 200,
    response: deviceEnrollmentCodeSchema,
  }),
  setDevicePerimeter: tenantEndpoint({
    operationId: 'setDevicePerimeter',
    method: 'put',
    path: '/devices/{id}/perimeter',
    summary: 'Affecter un terminal à des secteurs, ou au SIS entier (aucun secteur) ; suivi au prochain contact',
    tags: ['devices'],
    params: idParamsSchema,
    body: devicePerimeterSchema,
    concurrency: 'if-match',
    successStatus: 200,
    response: deviceSchema,
  }),
  revokeDevice: tenantEndpoint({
    operationId: 'revokeDevice',
    method: 'post',
    path: '/devices/{id}/revocation',
    summary: 'Révoquer un terminal : refus serveur immédiat, purge locale au prochain contact (OFF-04)',
    tags: ['devices'],
    params: idParamsSchema,
    body: deviceRevokeSchema,
    concurrency: 'if-match',
    successStatus: 200,
    response: deviceSchema,
  }),
  enrollDevice: tenantEndpoint({
    operationId: 'enrollDevice',
    method: 'post',
    path: '/sync/enrollment',
    summary: 'Enrôler ce terminal avec le code remis par l’administrateur et sa clé publique',
    tags: ['sync'],
    body: deviceEnrollSchema,
    successStatus: 201,
    response: deviceEnrollmentSchema,
  }),
  // SEC-05: the terminal moves to a new key (Android Keystore); signed by the current key, the new
  // one signing the rotation text. The previous key is refused from then on.
  rotateDeviceKey: tenantEndpoint({
    operationId: 'rotateDeviceKey',
    method: 'post',
    path: '/sync/device-key',
    summary: 'Remplacer la clé de ce terminal par une nouvelle clé qu’il détient (rotation signée)',
    tags: ['sync'],
    body: deviceKeyRotateSchema,
    deviceProof: true,
    successStatus: 200,
    response: deviceKeyRotationSchema,
  }),
  getTerminalPolicy: tenantEndpoint({
    operationId: 'getTerminalPolicy',
    method: 'get',
    path: '/settings/terminals',
    summary: 'Politique de verrouillage et de session des tablettes du SIS (administration)',
    tags: ['devices'],
    successStatus: 200,
    response: terminalPolicySchema,
  }),
  updateTerminalPolicy: tenantEndpoint({
    operationId: 'updateTerminalPolicy',
    method: 'put',
    path: '/settings/terminals',
    summary: 'Modifier la politique des tablettes (second facteur exigé, auditée, suivie au prochain catalogue)',
    tags: ['devices'],
    body: terminalPolicySchema,
    successStatus: 200,
    response: terminalPolicySchema,
  }),
  getSupervision: tenantEndpoint({
    operationId: 'getSupervision',
    method: 'get',
    path: '/supervision',
    summary: 'Tableau de supervision du SIS : publications, terminaux, signalements, fichiers, fonds (audit:read)',
    tags: ['supervision'],
    successStatus: 200,
    response: tenantSupervisionSchema,
  }),
  // Read before the catalogue (SEC-04): the terminal checks it with an embedded root key, refuses a
  // sequence older than its own, then trusts only the keys it lists.
  getSyncKeyset: tenantEndpoint({
    operationId: 'getSyncKeyset',
    method: 'get',
    path: '/sync/keyset',
    summary: 'Jeu de clés de signature signé par la clé racine (404 : aucun jeu configuré)',
    tags: ['sync'],
    deviceProof: true,
    successStatus: 200,
    response: signedKeysetSchema,
  }),
  getSyncCatalog: tenantEndpoint({
    operationId: 'getSyncCatalog',
    method: 'get',
    path: '/sync/catalog',
    summary: 'Catalogue signé des publications autorisées pour ce terminal (génération monotone)',
    tags: ['sync'],
    deviceProof: true,
    successStatus: 200,
    response: signedCatalogSchema,
  }),
  getSyncPackage: tenantEndpoint({
    operationId: 'getSyncPackage',
    method: 'get',
    path: '/sync/publications/{id}',
    summary: 'Manifeste signé et données d’une publication distribuée',
    tags: ['sync'],
    params: idParamsSchema,
    deviceProof: true,
    successStatus: 200,
    response: syncPackageSchema,
  }),
  createSyncDownloads: tenantEndpoint({
    operationId: 'createSyncDownloads',
    method: 'post',
    path: '/sync/publications/{id}/downloads',
    summary: 'URL de téléchargement (5 min) des fichiers d’une publication, par empreinte',
    tags: ['sync'],
    params: idParamsSchema,
    body: syncDownloadRequestSchema,
    deviceProof: true,
    successStatus: 200,
    response: syncDownloadsSchema,
  }),
  recordSyncReceipt: tenantEndpoint({
    operationId: 'recordSyncReceipt',
    method: 'post',
    path: '/sync/receipts',
    summary: 'Accuser l’installation : génération et publications actives sur le terminal',
    tags: ['sync'],
    body: syncReceiptSchema,
    deviceProof: true,
    successStatus: 200,
    response: syncReceiptResultSchema,
  }),
  getSyncBasemap: tenantEndpoint({
    operationId: 'getSyncBasemap',
    method: 'get',
    path: '/sync/basemaps/{id}',
    summary: 'Manifeste signé d’un fond de carte en vigueur pour un secteur du terminal',
    tags: ['sync'],
    params: idParamsSchema,
    deviceProof: true,
    successStatus: 200,
    response: syncBasemapSchema,
  }),
  createSyncBasemapDownloads: tenantEndpoint({
    operationId: 'createSyncBasemapDownloads',
    method: 'post',
    path: '/sync/basemaps/{id}/downloads',
    summary: 'URL de téléchargement (5 min) des parties d’un fond de carte, par empreinte',
    tags: ['sync'],
    params: idParamsSchema,
    body: syncDownloadRequestSchema,
    deviceProof: true,
    successStatus: 200,
    response: syncDownloadsSchema,
  }),
  recordSyncBasemapReceipt: tenantEndpoint({
    operationId: 'recordSyncBasemapReceipt',
    method: 'post',
    path: '/sync/basemaps/receipts',
    summary: 'Accuser les fonds de carte complets sur le terminal',
    tags: ['sync'],
    body: syncBasemapReceiptSchema,
    deviceProof: true,
    successStatus: 200,
    response: syncBasemapReceiptResultSchema,
  }),
  submitAccessEvents: tenantEndpoint({
    operationId: 'submitAccessEvents',
    method: 'post',
    path: '/sync/access-events',
    summary: 'Remonter les consultations hors ligne des sites sensibles (journal, idempotent par identifiant)',
    tags: ['sync'],
    body: syncAccessEventsSchema,
    deviceProof: true,
    successStatus: 200,
    response: syncAccessEventsResultSchema,
  }),

  // ---------------------------------------------------------------- field reports (OPS-04, ADR-017)
  submitFieldReport: tenantEndpoint({
    operationId: 'submitFieldReport',
    method: 'post',
    path: '/sync/reports',
    summary:
      'Transmettre un signalement terrain (une seule fois par identifiant du terminal) et obtenir les URL de dépôt des photos',
    tags: ['field-reports'],
    body: fieldReportSubmitSchema,
    deviceProof: true,
    successStatus: 200,
    response: fieldReportReceiptSchema,
  }),
  confirmFieldReportUploads: tenantEndpoint({
    operationId: 'confirmFieldReportUploads',
    method: 'post',
    path: '/sync/reports/{id}/uploaded',
    summary: 'Photos du signalement envoyées : demander leur contrôle',
    tags: ['field-reports'],
    params: idParamsSchema,
    deviceProof: true,
    successStatus: 202,
    response: fieldReportUploadedSchema,
  }),
  listSyncReports: tenantEndpoint({
    operationId: 'listSyncReports',
    method: 'get',
    path: '/sync/reports',
    summary: 'Suite donnée aux signalements de l’agent depuis ce terminal (90 derniers jours)',
    tags: ['field-reports'],
    deviceProof: true,
    successStatus: 200,
    response: syncReportsSchema,
  }),
  listFieldReports: tenantEndpoint({
    operationId: 'listFieldReports',
    method: 'get',
    path: '/field-reports',
    summary: 'Signalements terrain à instruire (ou instruits) dans le SIS actif',
    tags: ['field-reports'],
    query: fieldReportListQuerySchema,
    successStatus: 200,
    response: fieldReportListSchema,
  }),
  getFieldReport: tenantEndpoint({
    operationId: 'getFieldReport',
    method: 'get',
    path: '/field-reports/{id}',
    summary: 'Détail d’un signalement : constat, photos, version consultée et version actuelle',
    tags: ['field-reports'],
    params: idParamsSchema,
    successStatus: 200,
    response: fieldReportSchema,
  }),
  updateFieldReport: tenantEndpoint({
    operationId: 'updateFieldReport',
    method: 'patch',
    path: '/field-reports/{id}',
    summary: 'Instruire un signalement : prise en charge, affectation, intégration au brouillon, décision motivée',
    tags: ['field-reports'],
    params: idParamsSchema,
    body: fieldReportUpdateSchema,
    concurrency: 'if-match',
    successStatus: 200,
    response: fieldReportSchema,
  }),

  // ---------------------------------------------------------------- exploitant access (POR-01, ADR-019)
  listPortalInvitations: tenantEndpoint({
    operationId: 'listPortalInvitations',
    method: 'get',
    path: '/portal-invitations',
    summary: 'Invitations et accès des exploitants du SIS',
    tags: ['portal'],
    successStatus: 200,
    response: portalInvitationListSchema,
  }),
  createPortalInvitation: tenantEndpoint({
    operationId: 'createPortalInvitation',
    method: 'post',
    path: '/portal-invitations',
    summary: 'Inviter un exploitant sur un ou plusieurs sites (durée de validité, usage unique)',
    tags: ['portal'],
    body: portalInvitationCreateSchema,
    successStatus: 201,
    response: portalInvitationCreatedSchema,
  }),
  revokePortalInvitation: tenantEndpoint({
    operationId: 'revokePortalInvitation',
    method: 'post',
    path: '/portal-invitations/{id}/revocation',
    summary: 'Révoquer une invitation ou l’accès qu’elle a ouvert (fin immédiate)',
    tags: ['portal'],
    params: idParamsSchema,
    body: portalInvitationRevokeSchema,
    concurrency: 'if-match',
    successStatus: 200,
    response: portalInvitationSchema,
  }),
  listMyPortalInvitations: {
    operationId: 'listMyPortalInvitations',
    method: 'get',
    path: '/me/portal-invitations',
    summary: 'Invitations en attente de la personne connectée, dans tous les SIS',
    tags: ['portal'],
    auth: 'user',
    tenantScoped: false,
    successStatus: 200,
    response: myPortalInvitationListSchema,
  },
  acceptPortalInvitation: {
    operationId: 'acceptPortalInvitation',
    method: 'post',
    path: '/me/portal-invitations/{id}/acceptance',
    summary: 'Accepter une invitation (une seule fois, avant son expiration)',
    tags: ['portal'],
    auth: 'user',
    tenantScoped: false,
    params: idParamsSchema,
    successStatus: 200,
    response: portalInvitationAcceptedSchema,
  },
  getPortalSettings: tenantEndpoint({
    operationId: 'getPortalSettings',
    method: 'get',
    path: '/settings/portal',
    summary: 'Réglages du portail exploitant du SIS (second facteur exigé)',
    tags: ['portal'],
    successStatus: 200,
    response: portalSettingsSchema,
  }),
  updatePortalSettings: tenantEndpoint({
    operationId: 'updatePortalSettings',
    method: 'put',
    path: '/settings/portal',
    summary: 'Modifier les réglages du portail exploitant (administration du SIS)',
    tags: ['portal'],
    body: portalSettingsSchema,
    successStatus: 200,
    response: portalSettingsSchema,
  }),
  getEtareLayoutSettings: tenantEndpoint({
    operationId: 'getEtareLayoutSettings',
    method: 'get',
    path: '/settings/etare',
    summary: 'Sections facultatives masquées par le SIS dans l’ETARE (DEC-05)',
    tags: ['etare'],
    successStatus: 200,
    response: etareLayoutSettingsSchema,
  }),
  updateEtareLayoutSettings: tenantEndpoint({
    operationId: 'updateEtareLayoutSettings',
    method: 'put',
    path: '/settings/etare',
    summary: 'Masquer ou montrer des sections facultatives (administration du SIS, audité) ; figé à chaque soumission',
    tags: ['etare'],
    body: etareLayoutSettingsSchema,
    successStatus: 200,
    response: etareLayoutSettingsSchema,
  }),
  getPortalAccess: tenantEndpoint({
    operationId: 'getPortalAccess',
    method: 'get',
    path: '/portal/access',
    summary: 'Accès du demandeur au portail exploitant du SIS actif (accordé, second facteur requis, aucun)',
    tags: ['portal'],
    successStatus: 200,
    response: portalAccessSchema,
  }),
  listPortalSites: tenantEndpoint({
    operationId: 'listPortalSites',
    method: 'get',
    path: '/portal/sites',
    summary: 'Sites ouverts à l’exploitant dans le SIS actif, avec leur version publiée',
    tags: ['portal'],
    successStatus: 200,
    response: portalSiteListSchema,
  }),
  getPortalSite: tenantEndpoint({
    operationId: 'getPortalSite',
    method: 'get',
    path: '/portal/sites/{id}',
    summary: 'Ce que l’exploitant voit d’un site : liste blanche de la version publiée',
    tags: ['portal'],
    params: idParamsSchema,
    successStatus: 200,
    response: portalSiteSchema,
  }),
  getPortalDocumentDownload: tenantEndpoint({
    operationId: 'getPortalDocumentDownload',
    method: 'get',
    path: '/portal/sites/{id}/documents/{document_id}/download',
    summary: 'URL de courte durée d’un document publié visible de l’exploitant (accès tracé)',
    tags: ['portal'],
    params: portalDocumentParamsSchema,
    successStatus: 200,
    response: assetDownloadSchema,
  }),

  // ---------------------------------------------------------------- proposals of the exploitants (POR-03/04)
  createPortalContribution: tenantEndpoint({
    operationId: 'createPortalContribution',
    method: 'post',
    path: '/portal/sites/{id}/contributions',
    summary: 'Proposer une mise à jour d’un site (jamais une modification directe), avec ses pièces',
    tags: ['portal'],
    params: idParamsSchema,
    body: contributionCreateSchema,
    successStatus: 201,
    response: contributionReceiptSchema,
  }),
  confirmPortalContributionUploads: tenantEndpoint({
    operationId: 'confirmPortalContributionUploads',
    method: 'post',
    path: '/portal/contributions/{id}/uploaded',
    summary: 'Pièces d’une proposition envoyées : demande de leur contrôle (idempotent)',
    tags: ['portal'],
    params: idParamsSchema,
    successStatus: 200,
    response: contributionUploadedSchema,
  }),
  listPortalContributions: tenantEndpoint({
    operationId: 'listPortalContributions',
    method: 'get',
    path: '/portal/contributions',
    summary: 'Propositions de l’exploitant dans le SIS actif (d’un site ou de tous)',
    tags: ['portal'],
    query: portalContributionListQuerySchema,
    successStatus: 200,
    response: portalContributionListSchema,
  }),
  getPortalContribution: tenantEndpoint({
    operationId: 'getPortalContribution',
    method: 'get',
    path: '/portal/contributions/{id}',
    summary: 'Une proposition de l’exploitant : échanges, pièces et issue',
    tags: ['portal'],
    params: idParamsSchema,
    successStatus: 200,
    response: portalContributionSchema,
  }),
  replyPortalContribution: tenantEndpoint({
    operationId: 'replyPortalContribution',
    method: 'post',
    path: '/portal/contributions/{id}/messages',
    summary: 'Répondre au SIS sur une proposition (une demande de précision est alors satisfaite)',
    tags: ['portal'],
    params: idParamsSchema,
    body: contributionMessageCreateSchema,
    successStatus: 200,
    response: portalContributionSchema,
  }),
  withdrawPortalContribution: tenantEndpoint({
    operationId: 'withdrawPortalContribution',
    method: 'post',
    path: '/portal/contributions/{id}/withdrawal',
    summary: 'Retirer une proposition pas encore décidée (définitif)',
    tags: ['portal'],
    params: idParamsSchema,
    successStatus: 200,
    response: portalContributionSchema,
  }),
  listContributions: tenantEndpoint({
    operationId: 'listContributions',
    method: 'get',
    path: '/contributions',
    summary: 'Propositions des exploitants à instruire (ou instruites) dans le SIS actif',
    tags: ['contributions'],
    query: contributionListQuerySchema,
    successStatus: 200,
    response: contributionListSchema,
  }),
  getContribution: tenantEndpoint({
    operationId: 'getContribution',
    method: 'get',
    path: '/contributions/{id}',
    summary: 'Une proposition : valeur vue, proposée et actuelle, conflit, échanges, pièces',
    tags: ['contributions'],
    params: idParamsSchema,
    successStatus: 200,
    response: contributionSchema,
  }),
  updateContribution: tenantEndpoint({
    operationId: 'updateContribution',
    method: 'patch',
    path: '/contributions/{id}',
    summary:
      'Instruire une proposition : prise en charge, question à l’exploitant, intégration au brouillon, décision motivée',
    tags: ['contributions'],
    params: idParamsSchema,
    body: contributionUpdateSchema,
    concurrency: 'if-match',
    successStatus: 200,
    response: contributionSchema,
  }),

  // ---------------------------------------------------------------- notifications (POR-05)
  listNotifications: tenantEndpoint({
    operationId: 'listNotifications',
    method: 'get',
    path: '/notifications',
    summary: 'E-mails du portail exploitant du SIS actif : envoyés, en attente ou en échec',
    tags: ['notifications'],
    query: notificationListQuerySchema,
    successStatus: 200,
    response: notificationListSchema,
  }),
  retryNotification: tenantEndpoint({
    operationId: 'retryNotification',
    method: 'post',
    path: '/notifications/{id}/retry',
    summary: 'Renvoyer une notification (en échec ou perdue)',
    tags: ['notifications'],
    params: idParamsSchema,
    successStatus: 200,
    response: notificationSchema,
  }),
} as const satisfies Record<string, EndpointContract>;

export type EndpointName = keyof typeof endpoints;
export type EndpointResponse<N extends EndpointName> = z.infer<(typeof endpoints)[N]['response']>;
