import { existsSync } from 'node:fs';
import { resolve } from 'node:path';

const envFile = resolve(import.meta.dirname, '../../.env.local');
// Local runs read the file generated by `pnpm setup:local`; CI exports the same variables.
if (existsSync(envFile)) process.loadEnvFile(envFile);

export function requireEnv(name: string): string {
  const value = process.env[name];
  if (!value) throw new Error(`${name} is missing: run \`pnpm db:start\` then \`pnpm setup:local\`.`);
  return value;
}

export const DEMO_PASSWORD = 'Etare-Demo-2026!';
export const TENANT_06 = '06000000-0000-4000-8000-000000000000';
export const TENANT_83 = '83000000-0000-4000-8000-000000000000';
export const EHPAD_ID = '06000002-0000-4000-8000-000000000001';
export const SITE_83_ID = '83000002-0000-4000-8000-000000000001';

/** Signs in against the local Supabase Auth with a seeded demo account (synthetic data only). */
export async function signIn(email: string): Promise<string> {
  const response = await fetch(`${requireEnv('SUPABASE_URL')}/auth/v1/token?grant_type=password`, {
    method: 'POST',
    headers: { apikey: requireEnv('NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY'), 'content-type': 'application/json' },
    body: JSON.stringify({ email, password: DEMO_PASSWORD }),
  });
  const body = (await response.json()) as { access_token?: string };
  if (!response.ok || !body.access_token) throw new Error(`Sign-in failed for ${email} (${response.status}).`);
  return body.access_token;
}
