import logo from '@/assets/brand/firescape-logo.png';
import logoInverse from '@/assets/brand/firescape-logo-inverse.png';

/**
 * Product identity. The logos are generated by `pnpm brand:assets` from the
 * masters in assets/brand/ (see its README); color tokens live in
 * packages/ui/src/styles/globals.css.
 */
export const brand = {
  productName: 'FireScape',
  tagline: 'La connaissance opérationnelle du bâtiment.',
  /** Pictogram and name, for light backgrounds. */
  logo,
  /** Same logo in white and orange, for the navy bars. */
  logoInverse,
} as const;
