/**
 * Generates the local environment files from the running local Supabase stack:
 *   .env.local           (API, worker, integration tests)
 *   apps/web/.env.local  (Next.js loads env files from its own directory)
 * Both are gitignored. Local development only: never point these at a shared environment.
 */
import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');

function supabaseStatus(): Record<string, string> {
  let output: string;
  try {
    output = execFileSync('supabase', ['status', '-o', 'env'], {
      cwd: root,
      encoding: 'utf8',
      shell: process.platform === 'win32',
      stdio: ['ignore', 'pipe', 'pipe'],
    });
  } catch {
    console.error('Local Supabase is not running: start it with `pnpm db:start`.');
    process.exit(1);
  }
  const values: Record<string, string> = {};
  for (const line of output.split(/\r?\n/)) {
    const match = /^([A-Z_]+)="?(.*?)"?$/.exec(line.trim());
    if (match?.[1] && match[2] !== undefined) values[match[1]] = match[2];
  }
  return values;
}

const status = supabaseStatus();
const apiUrl = status['API_URL'];
const publishableKey = status['PUBLISHABLE_KEY'];
const dbUrl = status['DB_URL'];
if (!apiUrl || !publishableKey || !dbUrl) {
  console.error('Unexpected `supabase status` output (API_URL, PUBLISHABLE_KEY or DB_URL missing).');
  process.exit(1);
}

const db = new URL(dbUrl);
const roleUrl = (role: string, password: string) =>
  `postgresql://${role}:${password}@${db.hostname}:${db.port}${db.pathname}`;

// Role passwords come from supabase/seed.sql (local-only values).
const content = `# Generated by \`pnpm setup:local\` — LOCAL DEVELOPMENT ONLY, never commit.
APP_ENV=development
NEXT_PUBLIC_SUPABASE_URL=${apiUrl}
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${publishableKey}
SUPABASE_URL=${apiUrl}
DATABASE_URL=${roleUrl('etare_api', 'etare_api_local_only')}
WORKER_DATABASE_URL=${roleUrl('etare_worker', 'etare_worker_local_only')}
LOCAL_DATABASE_ADMIN_URL=${dbUrl}
`;

for (const target of ['.env.local', 'apps/web/.env.local']) {
  writeFileSync(resolve(root, target), content, { mode: 0o600 });
  console.log(`Wrote ${target}`);
}
