import {
  basemapManifestSchema,
  type BasemapManifest,
  type BasemapOverview,
  type BasemapSectorState,
  type BasemapSource,
  type Signature,
} from '@etare/contracts';
import {
  BASEMAP_DEVICE_BUDGET_BYTES,
  BASEMAP_MANIFEST_VERSION,
  BASEMAP_MAX_BYTES,
  BASEMAP_MAX_TILES,
  BASEMAP_PART_BYTES,
  BASEMAP_STYLE_FILE,
  BASEMAP_TILES_FILE,
  Conflict,
  DEFAULT_BASEMAP_TILE_PLAN,
  SIGNATURE_CONTEXTS,
  ServiceUnavailable,
  basemapBounds,
  basemapRenewAfter,
  canonicalJson,
  planBasemapTiles,
  type Bbox,
  type BasemapCoverage,
  type BasemapTilePlanOptions,
  type LonLat,
  type RequestContext,
} from '@etare/domain';
import type { ContentSigner, ObjectStoreAdmin, SessionFactory } from './ports';
import { inTenant } from './use-cases';

/**
 * Offline base maps of the tablets (CAR-01 to CAR-03, ADR-024). The worker
 * prepares one file per sector from the configured source; the rights gate
 * (approved offline rights, after the rights sheet) is checked before any
 * request to the source, by the administration and by the worker.
 */

/** Jobs of the worker: preparation of one base map, planning of the preparations. */
export const BASEMAP_BUILD_JOB = 'basemap.build';
export const BASEMAP_PLAN_JOB = 'basemap.plan';

// ------------------------------------------------------------------ ports
/** Cancellation of a preparation (lease lost, shutdown): an AbortSignal in the worker. */
export interface BasemapSignal {
  readonly aborted: boolean;
  throwIfAborted(): void;
}

export type BasemapRights = 'approved' | 'unverified' | 'forbidden';

/** Product the tiles come from, and its offline rights (architecture §13, one rights sheet per product). */
export interface BasemapSourceInfo {
  readonly id: string;
  readonly product: string;
  readonly attribution: string;
  readonly licenceName: string;
  readonly licenceUrl: string;
  /** Test data generated by the platform (never a real map). */
  readonly synthetic: boolean;
  readonly rights: BasemapRights;
  /** Reference of the rights sheet that approved the rights. */
  readonly rightsReference: string | null;
}

/** A file travelling with the tiles (style, pictograms). */
export interface BasemapStyleFile {
  readonly path: string;
  readonly content: Uint8Array;
  readonly mediaType: string;
}

export interface BasemapTileSource {
  readonly info: BasemapSourceInfo;
  /** Uncompressed vector tile (MVT), or null when the source has nothing there. */
  tile(z: number, x: number, y: number, signal: BasemapSignal): Promise<Uint8Array | null>;
  /**
   * Style of the tablet, with its placeholders ({{BASEMAP_DIR}}, {{GLYPHS}}), and the
   * pictograms it names: a map that still calls a server is not offline.
   */
  styleFiles(signal: BasemapSignal): Promise<{ style: Record<string, unknown>; files: readonly BasemapStyleFile[] }>;
}

export interface BasemapArchiveHeader {
  readonly bounds: Bbox;
  readonly center: LonLat;
  readonly centerZoom: number;
  readonly minZoom: number;
  readonly maxZoom: number;
  readonly metadata: Record<string, unknown>;
}

/** A finished archive (temporary file of the worker), read in parts for the upload. */
export interface BasemapArchive {
  readonly sizeBytes: number;
  readonly sha256: string;
  readonly tileCount: number;
  parts(partBytes: number): AsyncIterable<Uint8Array>;
}

/** Writes a PMTiles archive from tiles added in increasing tile id order. */
export interface BasemapArchiveWriter {
  /** Bytes of tile data written so far. */
  readonly dataBytes: number;
  add(tileId: number, content: Uint8Array): Promise<void>;
  finish(header: BasemapArchiveHeader): Promise<BasemapArchive>;
  /** Removes the temporary files (always called). */
  dispose(): Promise<void>;
}

export interface BasemapArchiveFactory {
  create(): Promise<BasemapArchiveWriter>;
}

export interface BasemapJob {
  readonly packId: string;
  readonly tenantId: string;
  readonly sectorId: string;
  readonly sectorName: string;
  readonly version: number;
  readonly sourceId: string;
  readonly siteCount: number;
  readonly coverage: BasemapCoverage;
}

export interface BasemapBuildResult {
  readonly manifest: BasemapManifest;
  readonly manifestHash: string;
  readonly signature: Signature;
  readonly files: readonly { sha256: string; sizeBytes: number; storageKey: string }[];
  readonly totalBytes: number;
  readonly tileCount: number;
  readonly renewAfter: Date;
}

/** Worker side of the base maps (dedicated database functions). */
export interface BasemapBuildStore {
  /** Asks for the planning of a slot (one job per slot whatever the number of workers). */
  schedule(slot: string): Promise<void>;
  /** Queues the preparations the SIS need with this source; returns how many. */
  plan(sourceId: string): Promise<number>;
  /** Starts a preparation: null when it is no longer to do. */
  start(packId: string, tenantId: string): Promise<BasemapJob | null>;
  /** Records an object before writing it (cleanup of an interrupted preparation). */
  recordObject(packId: string, tenantId: string, key: string): Promise<boolean>;
  complete(packId: string, tenantId: string, result: BasemapBuildResult): Promise<boolean>;
  fail(packId: string, tenantId: string, code: string, detail: string): Promise<boolean>;
  objectsToRemove(limit: number): Promise<{ packId: string; tenantId: string; keys: readonly string[] }[]>;
  markRemoved(packId: string): Promise<boolean>;
}

/** Administration side (device:manage). */
export interface BasemapRepository {
  overview(): Promise<BasemapSectorState[]>;
  /** Queues a preparation now (or returns the one already queued or running). */
  requestBuild(sectorId: string, sourceId: string): Promise<string>;
}

/** A base map as distributed to a terminal. */
export interface DistributedBasemap {
  readonly manifest: unknown;
  readonly manifestHash: string;
  readonly signature: Signature;
}

// ------------------------------------------------------------------ administration
export interface BasemapAdminDependencies {
  readonly sessions: SessionFactory;
  /** Source configured on the platform; null: no base map. */
  readonly source: BasemapSourceInfo | null;
}

export function basemapSourceState(source: BasemapSourceInfo | null): BasemapSource | null {
  if (!source) return null;
  return {
    id: source.id,
    product: source.product,
    attribution: source.attribution,
    licence_name: source.licenceName,
    licence_url: source.licenceUrl,
    synthetic: source.synthetic,
    rights: source.rights,
    rights_reference: source.rightsReference,
    usable: source.rights === 'approved',
  };
}

export function getBasemapOverview(deps: BasemapAdminDependencies, context: RequestContext): Promise<BasemapOverview> {
  return inTenant(deps.sessions, context, 'device:manage', async (session) => ({
    source: basemapSourceState(deps.source),
    sectors: await session.basemaps.overview(),
    device_budget_bytes: BASEMAP_DEVICE_BUDGET_BYTES,
  }));
}

export function requestBasemapBuild(
  deps: BasemapAdminDependencies,
  context: RequestContext,
  sectorId: string,
): Promise<BasemapOverview> {
  const source = deps.source;
  return inTenant(deps.sessions, context, 'device:manage', async (session) => {
    if (!source) throw new ServiceUnavailable('Aucune source de fonds de carte n’est configurée sur cette plateforme.');
    if (source.rights !== 'approved') {
      throw new Conflict(
        `Les droits hors ligne du produit « ${source.product} » ne sont pas validés : ` +
          'la fiche de droits doit être validée par le référent SIG avant toute préparation.',
      );
    }
    await session.basemaps.requestBuild(sectorId, source.id);
    return {
      source: basemapSourceState(source),
      sectors: await session.basemaps.overview(),
      device_budget_bytes: BASEMAP_DEVICE_BUDGET_BYTES,
    };
  });
}

// ------------------------------------------------------------------ preparation (worker)
export interface BasemapBuildDependencies {
  readonly store: BasemapBuildStore;
  /** Configured source; null: none (the preparation fails visibly). */
  readonly source: BasemapTileSource | null;
  readonly archives: BasemapArchiveFactory;
  readonly objects: ObjectStoreAdmin;
  /** Publication key (worker): signs the manifests the tablets verify. */
  readonly signer: ContentSigner | null;
  readonly sha256: (content: Uint8Array | string) => Promise<string>;
  /** UTF-8 bytes of a text (the style). */
  readonly utf8: (text: string) => Uint8Array;
  readonly now: () => Date;
  /** Tiles requested in parallel from the source (the source paces itself). */
  readonly concurrency?: number;
  readonly plan?: BasemapTilePlanOptions;
  readonly limits?: { readonly maxTiles: number; readonly maxBytes: number };
}

export type BasemapBuildOutcome = 'built' | 'skipped' | 'failed';

class BuildRefused extends Error {
  constructor(
    readonly code: string,
    readonly detail: string,
  ) {
    super(code);
  }
}

const basemapKey = (tenantId: string, packId: string, path: string) => `tenants/${tenantId}/basemaps/${packId}/${path}`;

const formatCount = (value: number) => value.toLocaleString('fr-FR');
const round5 = (value: number) => Math.round(value * 1e5) / 1e5;

/** Fetches the tiles in order, a few in advance; the writer receives them by increasing id. */
async function writeTiles(
  deps: BasemapBuildDependencies,
  source: BasemapTileSource,
  writer: BasemapArchiveWriter,
  tiles: ReturnType<typeof planBasemapTiles>,
  maxBytes: number,
  signal: BasemapSignal,
): Promise<void> {
  const concurrency = Math.max(1, deps.concurrency ?? 4);
  const pending: Promise<{ ok: true; value: Uint8Array | null } | { ok: false; error: unknown }>[] = [];
  let next = 0;
  const launch = () => {
    const tile = tiles[next++];
    if (!tile) return;
    pending.push(
      source.tile(tile.z, tile.x, tile.y, signal).then(
        (value) => ({ ok: true as const, value }),
        (error: unknown) => ({ ok: false as const, error }),
      ),
    );
  };
  for (let i = 0; i < concurrency; i++) launch();
  for (let index = 0; index < tiles.length; index++) {
    signal.throwIfAborted();
    const result = await pending[index];
    launch();
    if (!result) continue;
    if (!result.ok) throw result.error;
    const tile = tiles[index];
    if (tile && result.value && result.value.byteLength > 0) await writer.add(tile.id, result.value);
    if (writer.dataBytes > maxBytes) {
      throw new BuildRefused(
        'TOO_LARGE',
        `Fond trop volumineux (plus de ${formatCount(Math.round(maxBytes / 1_048_576))} Mo) : découpez le secteur.`,
      );
    }
  }
}

/**
 * Prepares the base map of a sector: tiles of the general view and of the
 * detail areas, PMTiles archive in parts, style and pictograms, signed
 * manifest. A refusal (rights, empty or oversized sector) fails the
 * preparation visibly; a transient error is thrown so the job is retried.
 */
export async function buildBasemap(
  deps: BasemapBuildDependencies,
  packId: string,
  tenantId: string,
  signal: BasemapSignal,
): Promise<BasemapBuildOutcome> {
  const job = await deps.store.start(packId, tenantId);
  if (!job) return 'skipped';
  const plan = deps.plan ?? DEFAULT_BASEMAP_TILE_PLAN;
  const limits = deps.limits ?? { maxTiles: BASEMAP_MAX_TILES, maxBytes: BASEMAP_MAX_BYTES };
  let writer: BasemapArchiveWriter | null = null;
  try {
    const source = deps.source;
    if (!source || source.info.id !== job.sourceId) {
      throw new BuildRefused('SOURCE_UNAVAILABLE', 'La source de ce fond n’est plus configurée sur la plateforme.');
    }
    if (source.info.rights !== 'approved') {
      throw new BuildRefused(
        'BASEMAP_RIGHTS',
        `Droits hors ligne du produit « ${source.info.product} » non validés (fiche de droits).`,
      );
    }
    const signer = deps.signer;
    if (!signer) throw new BuildRefused('SIGNING_KEY_MISSING', 'Clé de signature des publications absente du worker.');
    const bounds = basemapBounds(job.coverage, plan);
    const tiles = planBasemapTiles(job.coverage, plan);
    if (!bounds || tiles.length === 0) throw new BuildRefused('EMPTY_SECTOR', 'Aucun site localisé dans ce secteur.');
    if (tiles.length > limits.maxTiles) {
      throw new BuildRefused(
        'TOO_MANY_TILES',
        `Secteur trop étendu : ${formatCount(tiles.length)} tuiles (au plus ${formatCount(limits.maxTiles)}). ` +
          'Découpez-le.',
      );
    }

    writer = await deps.archives.create();
    await writeTiles(deps, source, writer, tiles, limits.maxBytes, signal);
    const center: LonLat = job.coverage.extent
      ? [(job.coverage.extent[0] + job.coverage.extent[2]) / 2, (job.coverage.extent[1] + job.coverage.extent[3]) / 2]
      : [(bounds[0] + bounds[2]) / 2, (bounds[1] + bounds[3]) / 2];
    const archive = await writer.finish({
      bounds,
      center,
      centerZoom: Math.min(13, plan.generalMaxZoom),
      minZoom: 0,
      maxZoom: plan.detailMaxZoom,
      metadata: {
        name: job.sectorName,
        attribution: source.info.attribution,
        description: `${source.info.product} — fond hors ligne FireScape, version ${job.version}`,
        version: String(job.version),
      },
    });
    if (archive.tileCount === 0) throw new BuildRefused('EMPTY_SOURCE', 'La source n’a fourni aucune tuile ici.');

    const stored: { sha256: string; sizeBytes: number; storageKey: string }[] = [];
    const upload = async (path: string, content: Uint8Array, mediaType: string) => {
      const key = basemapKey(tenantId, packId, path);
      if (!(await deps.store.recordObject(packId, tenantId, key))) throw new Error('BASEMAP_NOT_BUILDING');
      await deps.objects.upload(key, content, mediaType, { upsert: true });
      const sha256 = await deps.sha256(content);
      stored.push({ sha256, sizeBytes: content.byteLength, storageKey: key });
      return { sha256, size_bytes: content.byteLength };
    };

    const tileParts: { sha256: string; size_bytes: number }[] = [];
    let index = 0;
    for await (const part of archive.parts(BASEMAP_PART_BYTES)) {
      signal.throwIfAborted();
      tileParts.push(
        await upload(`${BASEMAP_TILES_FILE}.${String(index).padStart(3, '0')}`, part, 'application/octet-stream'),
      );
      index++;
    }
    const files: BasemapManifest['files'] = [
      {
        path: BASEMAP_TILES_FILE,
        sha256: archive.sha256,
        size_bytes: archive.sizeBytes,
        media_type: 'application/vnd.pmtiles',
        parts: tileParts,
      },
    ];
    const { style, files: extra } = await source.styleFiles(signal);
    const styleBytes = deps.utf8(JSON.stringify(style));
    for (const file of [{ path: BASEMAP_STYLE_FILE, content: styleBytes, mediaType: 'application/json' }, ...extra]) {
      const part = await upload(file.path, file.content, file.mediaType);
      files.push({ path: file.path, ...part, media_type: file.mediaType, parts: [part] });
    }

    const builtAt = deps.now();
    const renewAfter = basemapRenewAfter(builtAt);
    const totalBytes = files.reduce((sum, file) => sum + file.size_bytes, 0);
    const manifest: BasemapManifest = basemapManifestSchema.parse({
      manifest_version: BASEMAP_MANIFEST_VERSION,
      kind: 'basemap',
      pack_id: job.packId,
      tenant_id: job.tenantId,
      sector_id: job.sectorId,
      sector_name: job.sectorName,
      version: job.version,
      source: {
        id: source.info.id,
        product: source.info.product,
        attribution: source.info.attribution,
        licence_name: source.info.licenceName,
        licence_url: source.info.licenceUrl,
        synthetic: source.info.synthetic,
      },
      built_at: builtAt.toISOString(),
      renew_after: renewAfter.toISOString(),
      coverage: {
        bounds: [round5(bounds[0]), round5(bounds[1]), round5(bounds[2]), round5(bounds[3])],
        center: [round5(center[0]), round5(center[1])],
        general_max_zoom: plan.generalMaxZoom,
        detail_max_zoom: plan.detailMaxZoom,
        detail_radius_m: plan.detailRadiusMeters,
        detail_points: job.coverage.detail.map(([lon, lat]) => [lon, lat] as [number, number]),
      },
      tiles: BASEMAP_TILES_FILE,
      style: BASEMAP_STYLE_FILE,
      tile_count: archive.tileCount,
      total_bytes: totalBytes,
      files,
    } satisfies BasemapManifest);
    const text = canonicalJson(manifest);
    const completed = await deps.store.complete(packId, tenantId, {
      manifest,
      manifestHash: await deps.sha256(text),
      signature: signer.sign(SIGNATURE_CONTEXTS.basemap, text),
      files: stored,
      totalBytes,
      tileCount: archive.tileCount,
      renewAfter,
    });
    return completed ? 'built' : 'skipped';
  } catch (error) {
    if (error instanceof BuildRefused) {
      await deps.store.fail(packId, tenantId, error.code, error.detail);
      return 'failed';
    }
    throw error;
  } finally {
    await writer?.dispose();
  }
}

/** Planning slot of a quarter of an hour (UTC), the deduplication key of the planning job. */
export function basemapPlanningSlot(now: Date): string {
  const slot = new Date(Math.floor(now.getTime() / 900_000) * 900_000);
  return slot.toISOString().slice(0, 16);
}

/**
 * Plans the preparations (when the source may be used) and removes the files of
 * superseded or failed preparations.
 */
export async function planBasemaps(
  deps: { store: BasemapBuildStore; objects: ObjectStoreAdmin | null; source: BasemapSourceInfo | null },
  limit = 20,
): Promise<{ planned: number; removed: number }> {
  const planned = deps.source?.rights === 'approved' ? await deps.store.plan(deps.source.id) : 0;
  let removed = 0;
  if (deps.objects) {
    for (const pack of await deps.store.objectsToRemove(limit)) {
      for (const key of pack.keys) await deps.objects.remove(key);
      if (await deps.store.markRemoved(pack.packId)) removed++;
    }
  }
  return { planned, removed };
}
