import type { ResolvedAccess } from '@etare/domain';
import type { RequestSession } from './ports';

type Repositories = Omit<RequestSession, 'access' | 'confirmDeviceProof'>;
export type SessionOverrides = { [K in keyof Repositories]?: Partial<Repositories[K]> };

function unstubbed(name: string) {
  return async (): Promise<never> => {
    throw new Error(`${name} is not stubbed in this test`);
  };
}

/**
 * Test helper: a request session whose repositories fail loudly unless the
 * test provides them, so a use case can never touch an unexpected repository.
 */
export function stubSession(access: ResolvedAccess, overrides: SessionOverrides = {}): RequestSession {
  return {
    access,
    confirmDeviceProof: () => undefined,
    identity: {
      me: unstubbed('identity.me'),
      holdsWithSecondFactor: unstubbed('identity.holdsWithSecondFactor'),
      holdsOnPart: async () => false,
      ...overrides.identity,
    },
    account: {
      sessions: unstubbed('account.sessions'),
      revoke: unstubbed('account.revoke'),
      recoveryCodes: unstubbed('account.recoveryCodes'),
      regenerateRecoveryCodes: unstubbed('account.regenerateRecoveryCodes'),
      useRecoveryCode: unstubbed('account.useRecoveryCode'),
      ...overrides.account,
    },
    security: {
      get: unstubbed('security.get'),
      update: unstubbed('security.update'),
      ...overrides.security,
    },
    sites: {
      list: unstubbed('sites.list'),
      get: unstubbed('sites.get'),
      mapFeatures: unstubbed('sites.mapFeatures'),
      create: unstubbed('sites.create'),
      update: unstubbed('sites.update'),
      archive: unstubbed('sites.archive'),
      restore: unstubbed('sites.restore'),
      ...overrides.sites,
    },
    buildings: {
      listBySite: unstubbed('buildings.listBySite'),
      create: unstubbed('buildings.create'),
      update: unstubbed('buildings.update'),
      createLevel: unstubbed('buildings.createLevel'),
      updateLevel: unstubbed('buildings.updateLevel'),
      ...overrides.buildings,
    },
    classifications: {
      listBySite: unstubbed('classifications.listBySite'),
      create: unstubbed('classifications.create'),
      update: unstubbed('classifications.update'),
      ...overrides.classifications,
    },
    contacts: {
      listBySite: unstubbed('contacts.listBySite'),
      create: unstubbed('contacts.create'),
      update: unstubbed('contacts.update'),
      ...overrides.contacts,
    },
    externalIds: {
      listBySite: unstubbed('externalIds.listBySite'),
      create: unstubbed('externalIds.create'),
      ...overrides.externalIds,
    },
    documents: {
      listBySite: unstubbed('documents.listBySite'),
      create: unstubbed('documents.create'),
      addVersion: unstubbed('documents.addVersion'),
      update: unstubbed('documents.update'),
      ...overrides.documents,
    },
    assets: { get: unstubbed('assets.get'), ...overrides.assets },
    objects: {
      types: unstubbed('objects.types'),
      type: unstubbed('objects.type'),
      listBySite: unstubbed('objects.listBySite'),
      get: unstubbed('objects.get'),
      create: unstubbed('objects.create'),
      update: unstubbed('objects.update'),
      createPhoto: unstubbed('objects.createPhoto'),
      updatePhoto: unstubbed('objects.updatePhoto'),
      mapFeatures: unstubbed('objects.mapFeatures'),
      ...overrides.objects,
    },
    plans: {
      listBySite: unstubbed('plans.listBySite'),
      get: unstubbed('plans.get'),
      create: unstubbed('plans.create'),
      addRevision: unstubbed('plans.addRevision'),
      update: unstubbed('plans.update'),
      ...overrides.plans,
    },
    zones: {
      listBySite: unstubbed('zones.listBySite'),
      get: unstubbed('zones.get'),
      create: unstubbed('zones.create'),
      update: unstubbed('zones.update'),
      ...overrides.zones,
    },
    risks: {
      types: unstubbed('risks.types'),
      type: unstubbed('risks.type'),
      createType: unstubbed('risks.createType'),
      updateType: unstubbed('risks.updateType'),
      listBySite: unstubbed('risks.listBySite'),
      get: unstubbed('risks.get'),
      create: unstubbed('risks.create'),
      update: unstubbed('risks.update'),
      ...overrides.risks,
    },
    etare: {
      dossiers: unstubbed('etare.dossiers'),
      overview: unstubbed('etare.overview'),
      createRevision: unstubbed('etare.createRevision'),
      revision: unstubbed('etare.revision'),
      submit: unstubbed('etare.submit'),
      queue: unstubbed('etare.queue'),
      decide: unstubbed('etare.decide'),
      publication: unstubbed('etare.publication'),
      approvalOf: unstubbed('etare.approvalOf'),
      requestPublication: unstubbed('etare.requestPublication'),
      withdraw: unstubbed('etare.withdraw'),
      layoutSettings: async () => [],
      updateLayoutSettings: unstubbed('etare.updateLayoutSettings'),
      ...overrides.etare,
    },
    sectors: {
      list: unstubbed('sectors.list'),
      communes: unstubbed('sectors.communes'),
      save: unstubbed('sectors.save'),
      archive: unstubbed('sectors.archive'),
      ...overrides.sectors,
    },
    members: {
      list: unstubbed('members.list'),
      add: unstubbed('members.add'),
      update: unstubbed('members.update'),
      setPerimeter: unstubbed('members.setPerimeter'),
      resetSecondFactor: unstubbed('members.resetSecondFactor'),
      ...overrides.members,
    },
    devices: {
      list: unstubbed('devices.list'),
      get: unstubbed('devices.get'),
      create: unstubbed('devices.create'),
      setPerimeter: unstubbed('devices.setPerimeter'),
      renewCode: unstubbed('devices.renewCode'),
      revoke: unstubbed('devices.revoke'),
      enroll: unstubbed('devices.enroll'),
      syncDevice: unstubbed('devices.syncDevice'),
      catalog: unstubbed('devices.catalog'),
      package: unstubbed('devices.package'),
      packageFiles: unstubbed('devices.packageFiles'),
      receipt: unstubbed('devices.receipt'),
      ...overrides.devices,
    },
    fieldReports: {
      submit: unstubbed('fieldReports.submit'),
      photos: unstubbed('fieldReports.photos'),
      uploaded: unstubbed('fieldReports.uploaded'),
      forDevice: unstubbed('fieldReports.forDevice'),
      list: unstubbed('fieldReports.list'),
      get: unstubbed('fieldReports.get'),
      update: unstubbed('fieldReports.update'),
      ...overrides.fieldReports,
    },
    portal: {
      listInvitations: unstubbed('portal.listInvitations'),
      getInvitation: unstubbed('portal.getInvitation'),
      invite: unstubbed('portal.invite'),
      revoke: unstubbed('portal.revoke'),
      myInvitations: unstubbed('portal.myInvitations'),
      accept: unstubbed('portal.accept'),
      settings: unstubbed('portal.settings'),
      updateSettings: unstubbed('portal.updateSettings'),
      accessState: unstubbed('portal.accessState'),
      sites: unstubbed('portal.sites'),
      site: unstubbed('portal.site'),
      documentFile: unstubbed('portal.documentFile'),
      notifyInvitation: unstubbed('portal.notifyInvitation'),
      ...overrides.portal,
    },
    contributions: {
      submit: unstubbed('contributions.submit'),
      files: unstubbed('contributions.files'),
      uploaded: unstubbed('contributions.uploaded'),
      mine: unstubbed('contributions.mine'),
      mineOne: unstubbed('contributions.mineOne'),
      reply: unstubbed('contributions.reply'),
      withdraw: unstubbed('contributions.withdraw'),
      list: unstubbed('contributions.list'),
      get: unstubbed('contributions.get'),
      update: unstubbed('contributions.update'),
      ...overrides.contributions,
    },
    notifications: {
      list: unstubbed('notifications.list'),
      get: unstubbed('notifications.get'),
      retry: unstubbed('notifications.retry'),
      ...overrides.notifications,
    },
    jobs: { enqueue: unstubbed('jobs.enqueue'), ...overrides.jobs },
    audit: { record: unstubbed('audit.record'), ...overrides.audit },
  };
}
